### ISSUE TITLE
Failed to export detailed results on view status in sent message

### ISSUE THREAD

**Issue by WaldekBarros** [OfficeDev/microsoft-teams-apps-company-communicator#1001]
Guys, good night!

I am facing an error while exporting the report to verify the status of the message. Could you help me?

![image](https://user-images.githubusercontent.com/129632590/229380141-0272c6f4-f36f-492a-9125-726b77945e05.png)

**Comment by gsv022** [comment]
Hi @WaldekBarros ,
Thanks for raising the query. Could you please respond to the below queries.

- Is this export issue started showing up suddenly?
- Or is it happening from the start?

**Comment by gsv022** [comment]
@WaldekBarros , Please respond to the above queries

**Comment by WaldekBarros** [comment]
@gsv022, sorry for the delay in reply.

The error has always occurred with ordinary users.

I realized that the error does not occur with my user. I don't know if it's because I'm a Global Administrator.

I'm able to click "allow" and then the file is available on my OneDrive.

![image](https://user-images.githubusercontent.com/129632590/230744466-8e939f60-65a5-4445-9808-7fd7df856000.png)

**Comment by gsv022** [comment]
@WaldekBarros ,
Here is the workaround for the Export issue.

- Go to Azure Portal

- Click on the resource group that has been used for CC

- Go to Storage Account.

- Select Storage browser

- Go to Blob Containers

- Click on export data blobs.

- Copy the desired zip folder name from teams and search for required zip folder in export data blobs.

- Click on the zip folder that needs to download

<img width="957" alt="image" src="https://user-images.githubusercontent.com/98143492/233042860-c9513a31-0f39-4b36-910f-cd4b6198008e.png">

- Download the zip file.

<img width="957" alt="image" src="https://user-images.githubusercontent.com/98143492/233042860-c9513a31-0f39-4b36-910f-cd4b6198008e.png">

- Once the issue is resolved,  we will update you.

**Comment by WaldekBarros** [comment]
@gsv022 Thank you!
