### ISSUE TITLE
Conflict with existing ScmType: ExternalGit

### ISSUE THREAD

**Issue by KyleHammackRS** [OfficeDev/microsoft-teams-apps-company-communicator#1046]
Deployment fails with error {"code":"BadRequest","message":"There was a conflict. Conflict with existing ScmType: ExternalGit","details":[{"message":"There was a conflict. Conflict with existing ScmType: ExternalGit"},{"code":"BadRequest"},{}]}

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/36744497/dc44dcb8-bf70-491b-8447-cd29baa60cf2)

from what i can tell it looks like the source code deployment times out, then the powershell script is re-deploying the arm template. issue seems to happen when the powershell script redeploys the arm template, with a conflicting git.

tried testing this in another subscription just deploying one app service with sourcecontrol, then on success redeployed the arm template with same conflict error:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/36744497/ccb621c3-ceb0-430c-aaeb-bb705524997b)

**Comment by gsv022** [comment]
Hi @KyleHammackRS ,
Thanks for raising the query. Normally, This issue occurs when the resource like App service or function app tries to pull the code from external git, sometimes it fails to pull the code due to network issue which is not in our control. 

- To overcome the failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select  App Service from list of resources-->Go to Deployment Center-->Click on Settings

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- If the resource is not pointing to intended repository and  showing empty. Please connect to the external Git and point to the official repository.
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.

Hope we conveyed.

**Comment by KyleHammackRS** [comment]
@gsv022 not sure thats the issue here. As I mentioned above I can consistently reproduce this by successfully deploying the external git configuration and then deploying the same template again (which is what your powershell deployment does if the code deployment took too long to finish).

When I deploy the repository and it fails to pull the code I usually receive a 502 error, not the Git conflict.

**Comment by gsv022** [comment]
Following the issue internally

**Comment by KyleHammackRS** [comment]
thanks, will wait for an update.

related side note, from your troubleshooting docs it seems like its pretty common that your Git deployment takes longer than the ARM deployment timeout period. If that is the case, wouldn't it make more sense to deploy only the infrastructure with the ARM template and then deploy the code outside of that? You are already using Azure CLI in your powershell script, so couldn't you just deploy the code with "az webapp deployment source config" once all the Azure resources are already deployed? Seems like you could avoid the timeout issues and the Git conflicts that way.

**Comment by gsv022** [comment]
Hi @KyleHammackRS,
This is one of the possibilities. As this deployment is long process it will take good amount of time and its completely not in our control. To mitigate the risks associated with lengthy deployments, we can employ a strategic approach that enhances our control over the process. By breaking down the template into smaller, more manageable chunks and deploying them individually, we increase our chances of success.

**Comment by KyleHammackRS** [comment]
@gsv022 not sure what you mean. are you still following this internally or do you have a fix?

**Comment by glblinck** [comment]
@gsv022  For this issue, I'm also seeing customers with the same problem. Making sure that External Git is disconnected and then re-synced helps with the web app that's not syncing during deployment, but it doesn't lead to a successful deployment for the overall package. Without hitting redeploy on the whole ARM, you don't get the needed output entries to be able to continue the deployment. How can we get around the deployment error and get to a successful ARM deployment so that we can get the output entries to continue the installation?
