### ISSUE TITLE
Users not receiving messages

### ISSUE THREAD

**Issue by JG-OC** [OfficeDev/microsoft-teams-apps-company-communicator#1083]
Hi,

We have an issue whereby quite a large number of users are not receiving the messages sent out. This can be when a group is target or a specific team that a user is added to that has been identified not receiving the messages. 

We have updated to the latest version via a sync of the AppService and FunctionApps, performed various restarts of the services but they still do not get the messages. 

The users even do not appear in the messagetracking logs they just dont seem like its been sent to them at all.

**Comment by gsv022** [comment]
Hi @JG-OC ,
Thanks for raising the query. Please respond to the below queries.

- What was the version previously(before sync)?
- What is the count of users in the team? 
- Please share the success and failure count of the latest message.
- Make sure that there are no guest users type because the count of guest users will not be taken into consideration.
- How many users in your tenant have the teams license?

**Comment by gsv022** [comment]
Could you please respond to the above queries.

**Comment by JG-OC** [comment]
So we believe this has been cause by the user deleting the message from Teams. The bot cannot then send a message to the user they way around it is to:

Logged on, cleared cache from roaming

C:\Users\<User.Name>\AppData\Roaming\Microsoft\Teams\Cache\Cache_Data

Sometimes thats enough, if not is a reinstall of Teams. If anyone else could confirm their end user deleted the chat too and it fixed it?

**Comment by gsv022** [comment]
Hi @JG-OC ,
We have a backlog item related to user chat deletion already. And the workaround that has been suggested above is not working. Depending upon the bandwidth and based on priority the fix for the issue will be taken care in the future releases of CC.

**Comment by JG-OC** [comment]
Perfect thanks
