### ISSUE TITLE
Button URL - Sorry, you do not have permission to access this page.

### ISSUE THREAD

**Issue by Mykhailo-D** [OfficeDev/microsoft-teams-apps-company-communicator#1090]
Giving any URL in during post creation results in a message "Sorry, you do not have permission to access this page. Please contact your administrator to be granted permission."
1. New message
2. Fill in Title, Button title, Button Url
3. Choose recipients
4. Save as draft
5. Get "Sorry, you do not have permission to access this page" message

Provided button URLs are https ones. 
In the app insights there are no 403 responses.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/96050310/1263db2f-7855-4448-8042-ab7c62b0bfb2)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/96050310/c7480dc5-896f-49b2-98e2-7bd5859c50cd)

**Comment by v-jaygupta** [comment]
Hi @Mykhailo-D ,

Thank you for raising the issue for Company Communicator app.
Could you please send the screenshot of App service status, repo URL and branch that you are pointing to. To get that, please refer to the below screenshots - 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/115773960/f2b1c060-a883-40a7-9bc4-a1cc0d9ba90e)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/115773960/5e9f19db-7112-4c89-8b7c-f19b6ac86e52)

**Comment by Mykhailo-D** [comment]
Hi,

Here it is
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/96050310/7dc97051-ae54-48b3-b38c-7845ba1ca265)

**Comment by gsv022** [comment]
Please share the screenshot of logs section deployment status.
<img width="953" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/e8dc7744-56a8-4e2c-bea3-9e12cebdbb93">

**Comment by gsv022** [comment]
Hi @Mykhailo-D ,

- Since it is a older version CC, was it working previously?

- There is a chance of incorrect configuration, have a thorough check from start-end and mainly verify the all three app client secret is correctly copied while creating ARM template or not. Attaching the [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/911) where you can compare and check on secrets. **Make sure to check the expiration date for app secrets**
- Please cross verify the set-up authentication part again. 
<img width="673" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/5d97b1ef-a490-46df-93bf-f403aab579df">

- Check whether the **Supported type** parameter for app registration is as per the deployment guide. Here is the reference.
    Author-multiple
    User-multiple
    Graph-my organization
<img width="686" alt="image" src="https://user-images.githubusercontent.com/98143492/221160735-4a1f8b6f-7361-4f67-ba7b-0d5c2d24ec17.png">

**Comment by Mykhailo-D** [comment]
Hi,
Checking configuration and whether the certs are expired was the first thing I did.
And yes, it was working previously.

**Comment by gsv022** [comment]
@Mykhailo-D , Please share your outlook id (mail id) so that we can discuss the issue internally.

**Comment by gsv022** [comment]
Please let us know if the error persists otherwise we can make it to closure.

**Comment by Mykhailo-D** [comment]
Redeploying whole CC appeared to be the quickest solution.
Ticket can be closed, thank you.
