### ISSUE TITLE
Unable to view the draft messages and sent messages

### ISSUE THREAD

**Issue by PrithuMahisha** [OfficeDev/microsoft-teams-apps-company-communicator#1095]
Getting the error shown in the below screenshot while we try to view the draft messages and sent messages.
However, we are able to create a new message without any issue. Please provide assistance ASAP.

Troubleshooting done so far:
Tried clear cache and reinstall Teams app
Remove Company Communicator app from the Team and re-add
Checked in Teams web app - same behavior.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/15922771/e5c52107-d96c-4dd3-9967-6cd157211f49)

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
Thanks for raising the query. This could be due to configuration issue only. Please check the configuration end-end. Mainly, check the deployment status of app service and function apps
<img width="959" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/57718222-7b09-46c1-b2f7-0f288b7cb6cc">

**Comment by PrithuMahisha** [comment]
Hi @gsv022 , Thanks for providing inputs.
The issue has been resolved. This can be closed.
It was due to the expiry of client secrets - we renewed it and it is working fine now.
Thanks!

**Comment by gsv022** [comment]
@PrithuMahisha , Thank you for the update.
