### ISSUE TITLE
Is it required that the bot is pre-installed?

### ISSUE THREAD

**Issue by cTallberg** [OfficeDev/microsoft-teams-apps-company-communicator#1112]
Trying to understand the documentation if it´s required to pre-install the bot in Teams for each user.
As per my understanding, if the user does not have the bot pre-installed, the Teams app will try to install the app automatically for the user? Is that the case?

**Comment by gsv022** [comment]
Hi @cTallberg ,
Thanks for raising the query. Our CC application is having a feature called **Proactive installation**, this will install the user bot to each user within a team. The user bot installation will be taken care of during the send operation of the message. 

**Note**:- Since Proactive installation is Boolean type, it is set to true by default during the ARM template filling so that user app will be installed automatically to the users for whom we intend to deliver the message. If it is set to false, then user app has to be manually installed for each one within the team.

Hope it is conveyed.
