### ISSUE TITLE
How to securely deploy Microsoft Teams App Company Communicator for my company?

### ISSUE THREAD

**Issue by albert-widjaja** [OfficeDev/microsoft-teams-apps-company-communicator#1115]
I'm currently planning to deploy Microsoft Teams App Company Communicator using the steps described in [https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide](https://learn.microsoft.com/en-us/answers/questions/1340452/deploying-frontdoor-in-front-of-the-app-service-fo?page=1&orderby=Helpful&comment=answer-1298445)

Since it is quite a complex IaaS offering on Azure Platform to deploy and requires regular maintenance and monitoring from the back end Azure Infrastructure, I wonder if anyone here can clarify about the Web Front end security.

1. Does the Azure FrontDoor service have to be deployed separately for this Teams Company Communicator to work or is it possible to reuse the existing production Azure Front Door instance?
2. What changes would need to be made to the existing instance to make it compatible with Teams Company Communicator?
3. What are the benefits of using Azure FrontDoor in front of the Azure App Service for this Microsoft Teams App Company Communicator ?

Your comments and suggestions are greatly appreciated.

**Comment by gsv022** [comment]
Hi @albert-widjaja ,
Thanks for raising the query. 

- _Does the Azure FrontDoor service have to be deployed separately for this Teams Company Communicator to work or is it possible to reuse the existing production Azure Front Door instance?_ Azure Front Door resource needs to be installed separately. But this will be taken care while the deployment is going on.
- _What changes would need to be made to the existing instance to make it compatible with Teams Company Communicator?_
It can be done. The configuration present in the frontdoor has to be updated and point it to the existing front door and the same needs to be updated in multiple places like Graph app- authentication, manifest files, at all configuration sections. We can't confirm on the functionality because we haven't tried this at our end. But these are the steps that can be tried.
- _What are the benefits of using Azure FrontDoor in front of the Azure App Service for this Microsoft Teams App Company Communicator ?_ The main use case of Azure FrontDoor is to handle the large amount of traffic and distribute across different loads whenever we are sending the message. It acts as a load balancer.

**Comment by gsv022** [comment]
Please let us know if you have any queries
