### ISSUE TITLE
Regarding App Registration

### ISSUE THREAD

**Issue by sponlinedev** [OfficeDev/microsoft-teams-apps-company-communicator#1185]
Below is our enviornment 
Azure Solution (Functions , App Service etc) are deployed in **Tenant 1**
Teams App and App Registration are done in **Tenant 2**

during the ARM deployment it was mentioned as subscription.tenant id (tenant1)
what are the places we need to chnage the tenant 2? and also in our organisation app registration is not allowed only for single tenant not multi tenant.  What is the impact on communicator app deployment and usage with app registration and single tenant ?

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/57736182/5c87a8fb-7cd2-4f3c-9225-79f83a1ad7bd)

**Comment by gsv022** [comment]
Hi @sponlinedev ,
Thank you for raising the query. 

- _Azure Solution (Functions , App Service etc) are deployed in Tenant 1
Teams App and App Registration are done in Tenant 2_
This is cross-tenant deployment where app registrations has been done in one tenant(tenant 2) and ARM template creation in another tenant(Tenant 1). Here **subscription.tenant id** parameter within the ARM template should be filled with id of  (**tenant 2**) because app will be deployed at **tenant 2** and moreover app registration is done at **tenant 2**

- _what are the places we need to chnage the tenant 2?_
   Please provide more inputs on this query

- _and also in our organization app registration is not allowed only for single tenant not multi tenant. What is the impact on communicator app deployment and usage with app registration and single tenant ?_
As per the deployment guide, **author and user app** should be kept as **Multiple Org** where as Graph app should be kept as **My Organization** otherwise the functionality would break for sure. The reason for choosing single tenant for graph app is to obtain logs, analytics etc., that should be restricted within organization only.

**Comment by sponlinedev** [comment]
we use ARM template to deploy , we had several failuer each time different issue , Finally it was sucessfull so we prefer not to deploy the ARM template again .

hence i would prefer to update the tenant id in the configuration and would like to know where are the places / configuration files i need to update the tenant id

**Comment by gsv022** [comment]
Hi @sponlinedev ,
Here are the places tenant id need to be updated. 
<img width="708" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/66f0ace2-ec4c-4f24-9418-05791aa5455d">

<img width="648" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/9dc0272b-0b11-4c7e-8fe5-5a52ae05e194">

- Save it and do restart in the overview section.

**Comment by sponlinedev** [comment]
besides the function environment variable are there any other places where need to change tenant id ?

Also how do we update the seceret id values when existing secret are expired or expiring

**Comment by gsv022** [comment]
Updating tenant id would be enough in those three places. Coming to updating the secret values, please refer to this issue- #1125

**Comment by sponlinedev** [comment]
Thanks for the information , will look into the reference for issue on updating the secret.
I have rasied another issue would be great if we can get some inputs on this 
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1187

this issue can be closed

**Comment by gsv022** [comment]
Hi @sponlinede
