### ISSUE TITLE
Multitenant App Registration Any Possible Security Risks

### ISSUE THREAD

**Issue by weixian-zhang** [OfficeDev/microsoft-teams-apps-company-communicator#1189]
Hi @sponlinedev ,
Thank you for raising the query. By switching to the supported account type as **my organization** for author and user bots it will break the functionality. As of now, there is no workaround for this requirement.

_Originally posted by @gsv022 in https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1187#issuecomment-1780750650_

**Comment by weixian-zhang** [comment]
Hi,

I have a couple of questions regarding security:

- Is there any potential security risks of allowing other tenants' users to sign into CC App?
- any potential security risks that users should take note and safe-guard against?

Thanks.

**Comment by gsv022** [comment]
Hi @weixian-zhang ,
Thanks for raising the query. 
- Bot Framework SDK's works usually on the multi-tenant app type only. Otherwise the functionality breaks for sure. Here is the [reference](https://learn.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0&tabs=userassigned#manual-app-registration).
<img width="462" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/18b6f0c1-9b78-4968-ae84-bbd7f9f20ce0">

- We have taken care of security risks at various levels by having proper authentication and authorization. There is a parameter called-"AuthorizedSenderUPN" within App service, only who have their UPN's within that parameter will have access to the application. 
- We have key vault as one of the resources to mask the app secrets and storage account connections etc.,
- There is a parameter called-"AuthorizedDeleteUPN" within App service, only who have their UPN's within this parameter will have access to the deletion of sent message records.
- It is fine to proceed with the deployment process that we published [here](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide)

**Comment by weixian-zhang** [comment]
Thanks for the informative response @gsv022.

Just want to confirm which App Setting(s) in CC App will allow only users to sign-in, from the "resident" Entra tenant where the 3 registered Entra apps reside?

Or is this "sign in from resident tenant only" behaviour a default all along and CC App will never allow users from other tenants to sign-in?

**Comment by gsv022** [comment]
@weixian-zhang ,
The tenant where app registration is done and only the users from that tenant-azure active directory will have the eligibility to access the application

**Comment by weixian-zhang** [comment]
Thanks @gsv022, that is exactly what we needed.

I understand that recently Bot framework SDK supports Single-Tenant and Managed Identity, as seen [here](https://learn.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0&tabs=userassigned) and [here](https://learn.microsoft.com/en-us/answers/questions/308518/bot-framework-app-registration-single-tenant-vs-mu).  
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/43234101/a76b709a-70dd-4712-8898-9b76e20bbbc2)

Just wish to clarify that registering User and Author Bot identities as Single-Tenant is now possible due to the fact that Bot framework v4 now supports Single Tenant and MI, however this is not in CC App's roadmap currently?

**Comment by gsv022** [comment]
Hi @weixian-zhang ,
Currently, we don't have any ETA on single tenant support for CC. We have taken a note of it and will be discussing with our internal team and proceed accordingly.
