### ISSUE TITLE
How do we change author UPN after the deployment

### ISSUE THREAD

**Issue by sponlinedev** [OfficeDev/microsoft-teams-apps-company-communicator#1194]
How do we change author UPN  after the deployment of azure solution and teams app.  

Like after the change if the we need to add more user who can author or remove existing user who have author role 

can we have the security group in UPN

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/57736182/181056c9-0d82-43b5-bf4c-948bfe0c9ef0)

**Comment by gsv022** [comment]
Hi @sponlinedev ,
Thank you for raising the query. Here is the place where UPN can be updated. 

- Go to resource group-->Click on app service/web app-->Goto configuration section(old)/environment variables(new)-->add/remove 'n' number of UPN within AuthorizedCreatorUPN's.

<img width="857" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/ddfe09a1-7212-48df-99dd-397449e176b0">

- Separate each UPN with semicolon(;)
- We recommend to go with individual UPN instead of security group UPN.

**Comment by sponlinedev** [comment]
What if we have a usecase where there will be frequent updates to the author.  Adding security group breaks any function?

We thought having security grp is eazy to manage rather than chnage the configuration in app serveice.

**Comment by gsv022** [comment]
Hi @sponlinedev ,
Newly added authors will be able to access the application unless Individuals UPN's are added . The users who are in the DL won't get access to the application because keeping DL within 'senderUPN' won't work.
