### ISSUE TITLE
Company Communicator Stopped Working

### ISSUE THREAD

**Issue by KassieNav** [OfficeDev/microsoft-teams-apps-company-communicator#1201]
I've not made any change for a few months and now get this error message: 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/111309340/1a3fb180-6033-404e-8f0f-ec13ac4908c5)

**Comment by gsv022** [comment]
Hi @KassieNav ,
Thanks for raising the query. We are checking this issue on priority and keep you posted.

**Comment by Fadel1949** [comment]
Yes, it is also a problem. Please help solve this problem. Thank you very much.

FYI: The problem occurs when using newer versions of Teams.

**Comment by ahlim0011** [comment]
Any fix for this

**Comment by ahlim0011** [comment]
my issue is happening on the old teams

**Comment by weixian-zhang** [comment]
I am having the same issue, I have not make any change since successful tests on 9th Nov, now is not working.  

<img width="1128" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/43234101/94141d53-622c-44a2-9d21-4d116d1ae84a">

**Comment by gsv022** [comment]
Hi @KassieNav ,
Thank you for the patience. 

- The app service authentication issue is now resolved, and the changes have been pushed to Company Communicator GitHub repository. 

- If current version of the Company Communicator application is pointing to v5.5, please follow the below procedure to resolve the issue 
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App(App Service) --> Go to Deployment Center --> Click on SYNC

- Once the status shows successful within logs section of Deployment Center.
<img width="833" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/9eb1d9a7-02f0-4583-8cd5-6f257eaa9ba8">

 
**Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service 
 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6e5045cb-27de-4e4f-9d22-7a7ef300888a)


- Please go to the Overview Section from and restart the app service.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6bb3fe8e-dbf2-4763-98f8-730460dd556d)

- Try accessing the CC application on Teams web client to avoid any cache related issue.

- If current deployed version of the Company Communicator application is pointing to v5.4.1 or previous versions, please upgrade your app to latest version by following the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide) as the fix is pushed to the main branch in Company Communicator's GitHub repo.

 
Please let us know if you are still facing the issue.
