### ISSUE TITLE
Cant upload app to teams 

### ISSUE THREAD

**Issue by ahlim0011** [OfficeDev/microsoft-teams-apps-company-communicator#1203]

**Comment by Hejhejhalla** [comment]
Hello,
Install the "Developer portal" app in Teams and use this tool:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/145015339/f0e0e24b-755b-40fb-8b17-b39ba58abb38)

**Comment by ahlim0011** [comment]
Thank you, below is the error I get when I try to import

Package Loading Failure Provided add-in package was not understood. Please, make sure that the file being submitted is a valid Office add-in package.

**Comment by ahlim0011** [comment]
[company-communicator-authors.zip.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/13296672/company-communicator-authors.zip.zip)

Same issue :( do you know if it has anything to do with my code? Sorry to ask but are you able to review and check for me?

I have been trying everything for the past few hours and it's driving me mad.

**Comment by Hejhejhalla** [comment]
Hi,
Try this one, it was successful for me.
On your last section you were missing a character. :)

[communicator-hasfeld.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/13296770/communicator-hasfeld.zip)

**Comment by ahlim0011** [comment]
thank you! now I have the below error

Error while reading manifest.json: bots[0].supportsCalling | Property "supportsCalling" has not been defined and the schema does not allow additional properties.; bots[0].supportsVideo | Property "supportsVideo" has not been defined and the schema does not allow additional properties.

do you know if we can have a call or remote session for you to help me get this resolved and tested. Sorry I am fairly new at doing this and would be grateful for any help.

**Comment by ahlim0011** [comment]
can anyone else help?

**Comment by gsv022** [comment]
Hi @ahlim0011 ,
Thank you for raising the query.  I have checked the latest manifest file. There is one character missing. It has been updated correctly. Most importantly "No need of mentioning the file type to the name again". This is taken care automatically. Please remove them and upload it. It works
[CC-author-Hausfeld.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/13304052/CC-author-Hausfeld.zip)

<img width="311" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/8769b6a1-dd72-42b4-8eea-60f2e391c4d2">




> [company-communicator-authors.zip.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/13296672/company-communicator-authors.zip.zip)
> 
> Same issue :( do you know if it has anything to do with my code? Sorry to ask but are you able to review and check for me?
> 
> I have been trying everything for the past few hours and it's driving me mad.

**Comment by ahlim0011** [comment]
Hi, 

The issue I am having now is different, the app updates on to teams but it just has the below issue 
![Screenshot 2023-11-08 204120](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150195103/14c7fa77-4483-4334-a314-3fcb3b8d6dcd)
with it going around in circle, do you have any idea on what is causing this issue? I didn't change the .zip you mentioned above but if that was the case the app wouldn't even update correct?


![Screenshot 2023-03-01 091644](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150195103/e920e56c-e5bb-4a3b-9bde-9d2471a20890)

**Comment by ahlim0011** [comment]
works now, but having a separate issue :(.... sorry to ask but are we able to jump on a call to help me resolve this?

**Comment by ahlim0011** [comment]
![Screenshot 2023-11-08 204120](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150195103/b4fb9680-8d0a-4463-b7e7-d5a9d29e3c55)

this is the error I am getting now

**Comment by Hejhejhalla** [comment]
They are looking into that issue, it came up on Monday I believe..

**Comment by ahlim0011** [comment]
do I need to install user one for now?

**Comment by gsv022** [comment]
Hi @ahlim0011 ,

- There is an ongoing issue with the app service authentication and we are currently liaising with the internal team for the issue resolution. We are checking this issue on priority . We will keep you posted.

> ![Screenshot 2023-11-08 204120](https://user-images.githubusercontent.com/150195103/281717109-b4fb9680-8d0a-4463-b7e7-d5a9d29e3c55.png)
> 
> this is the error I am getting now

- Coming to the user manifest, please do the same as author manifest. Yup, you can add it to the desired team.

**Comment by ahlim0011** [comment]
Slightly confused on how this works now, do all users need to be on a channel for this to work

**Comment by gsv022** [comment]
Hi @ahlim0011 ,
Thank you for the patience. 

- The app service authentication issue is now resolved, and the changes have been pushed to Company Communicator GitHub repository. 

- If current version of the Company Communicator application is pointing to v5.5, please follow the below procedure to resolve the issue 
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App(App Service) --> Go to Deployment Center --> Click on SYNC

- Once the status shows successful within logs section of Deployment Center.
<img width="833" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/9eb1d9a7-02f0-4583-8cd5-6f257eaa9ba8">

 
**Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service 
 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6e5045cb-27de-4e4f-9d22-7a7ef300888a)


- Please go to the Overview Section from and restart the app service.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6bb3fe8e-dbf2-4763-98f8-730460dd556d)

- Try accessing the CC application on Teams web client to avoid any cache related issue.

- If current deployed version of the Company Communicator application is pointing to v5.4.1 or previous versions, please upgrade your app to latest version by following the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide) as the fix is pushed to the main branch in Company Communicator's GitHub repo.

 
Please let us know if you are still facing the issue.
