### ISSUE TITLE
Can't open

### ISSUE THREAD

**Issue by ahlim0011** [OfficeDev/microsoft-teams-apps-company-communicator#1208]
Hi,

**Comment by gsv022** [comment]
Hi @ahlim0011 ,
Thank you for raising the query. There are multiple reasons for this issue.

Please cross verify the secrets. Here is the procedure for comparison. 

- Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault  from list of resources

- Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret.

**Comment by ahlim0011** [comment]
Hi,

Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

I cant view the  secret value now :( any other wat I can see this

**Comment by ahlim0011** [comment]
![Screenshot 2023-11-10 103612](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150195103/857072d4-508b-43d5-bd25-3da59c933733)

I checked the ones highlighted in yellow and they are matching the secret ID from app registration.  Do you know if I need to check the others and if so how I can find them. 

Also I don't get what the below step was needed for so if you can please help
Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

**Comment by ahlim0011** [comment]
any update for me on this please

**Comment by gsv022** [comment]
Hi @ahlim0011 ,
As you mentioned that 
_I checked the ones highlighted in yellow and they are matching the **secret ID** from app registration. Do you know if I need to check the others and if so how I can find them._


Could you please compare and confirm whether the app registration secret **value**(the first three values) are matching with the app secrets present in key vault or not.

**Comment by ahlim0011** [comment]
slightly confused on what to do? Are we able to have a call, this will really help me

**Comment by ahlim0011** [comment]
the secret ID and values match to me, but some of them I don't know how to check

**Comment by ahlim0011** [comment]
can you let me know how I see thee app secrets present in key vault only gives me option to see key vault

**Comment by gsv022** [comment]
Hi @ahlim0011 ,

- Great, you have already opened key vault-->Secrets. Now, open authorapppassword-->open current version-->show secret value--> the first three values of secret should match with author app registration-->certificates and secrets -->Compare with secret value(not secret id)
- If it is already done and are same only then share the zipped manifest files of author and user(where you have updated bot id's and app domain)

**Comment by ahlim0011** [comment]
![send](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150195103/d1b31127-1536-4cee-bd76-389a5efa5c60)
![send new](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150195103/9e432e1f-b143-422f-bf0a-b9d5492aeaf2)

Is this what you're referring too?

**Comment by gsv022** [comment]
Hi @ahlim0011 ,
It seems that you copied secret id instead of secret value. We recommend you to create a new secret. Update it in respective places. Here is the procedure.

- Go to Azure Portal
- Go to App registration
- Create a new secret value for app registration and grab secret value. Here is the reference.
<img width="793" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/62fb1be1-0fa3-47d4-ad7e-5851e5fd45a7">

- Then go to resource group. Select key vault from list of resources.
- Click on secrets under object section.
<img width="918" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/b4e29cd5-2fe8-4b15-a0ce-08245346683f">
- If the secrets are not visible, Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. Open author/user/graph app password
- Click new version
<img width="359" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/eec3cc6d-1455-477f-8918-dd44eb5b2290">

- Grab the new  secret identifier 
<img width="516" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/046b83b5-e8b6-42f4-a4e6-8184cb8d9584">

- Paste it in the configuration sections of  app service, 3-function apps. Here is the reference of updating the author app password in app service configuration. 
<img width="779" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d9444a9a-fe5b-4d09-8f96-53b70ab40121">

-  Follow the same procedure for the user app password and graph app password updating.

- For graph app, please dont forget to  update the password in **AzureAd Client Secret** as well. here is the reference
<img width="574" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/287f2d3b-52a7-41bf-852e-541de7ccf02a">

**Comment by ahlim0011** [comment]
Hello, I'm a bit uncertain about the process. Would it be possible to schedule a brief Teams call? I've dedicated a couple of weeks to this, and your guidance would be invaluable. I noticed that I might have copied the secret ID instead of the secret value. Could you clarify how I should proceed with updating this based on your instructions

**Comment by ahlim0011** [comment]
can anyone help?

**Comment by gsv022** [comment]
Hi @ahlim0011 ,
Please share your mail id(outlook id/teams id) so that we can discuss the issue internally

**Comment by ahlim0011** [comment]
email is ahalim@hausfeld.com

**Comment by gsv022** [comment]
@ahlim0011 , We will continue the conversation internally.

**Comment by gsv022** [comment]
Hi @ahlim0011 ,
We Joined the call and observed that secrets were incorrectly configured. It is sorted and messages are getting delivered. Please feel free to open a new issue if anything comes with CC functional or deployment issues.
