### ISSUE TITLE
Author app shows error when opening within "new" Teams on desktop and web

### ISSUE THREAD

**Issue by HealthyGranty** [OfficeDev/microsoft-teams-apps-company-communicator#1212]
Seemingly Company Communicator does not work in "new" Teams, desktop or web.
Version
You have Microsoft Teams version 23285.3604.2469.4152.
You've got the latest version. It was last updated on 10/11/2023.
The client version is 49/23101227708.

When accessing the Author app in "new" Teams, the sections for draft, scheduled, sent appear for a second or so, then the error below appears.
Sorry, an error occurred while trying to access this service.

Accessing the Author app in "old" Teams the app is working correctly.

**Comment by HealthyGranty** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150428782/93aca9c2-241b-4de6-8e54-07c253da9ab2)
I believe this helps you understand the version etc. Let me know if any other information required.

**Comment by gsv022** [comment]
Hi @HealthyGranty ,
Thank you for raising the query. There is an ongoing issue with the app service authentication and we are currently liaising with the internal team for the issue resolution.
We are checking this issue on priority . We will keep you posted.

**Comment by David-hughes8** [comment]
Same issue here - any progress ?

**Comment by frankiem168** [comment]
I got a same issue; may I know if there is fix schedule?

**Comment by dahazeman** [comment]
Please notify me when this issue is fixed.

**Comment by danielmacedo90** [comment]
I have the same problem.

Just to contribute, I noticed that the problem is related to the use of frontdoor, more specifically in routingrules2.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/32306990/c96d081d-865f-4e2c-b0b1-60a8db2a472e)


When the redirect is done through the frontdoor, the authorization headers are not sent, causing an error in the MustBeValidUpnPolicy policy.

**Comment by spiritgolfer** [comment]
Same issue here as well, using Teams classic works for now.  That's of course until MS takes away that option!

**Comment by gsv022** [comment]
Hi @HealthyGranty ,
Thank you for the patience. 

- The app service authentication issue is now resolved, and the changes have been pushed to Company Communicator GitHub repository. 

- If current version of the Company Communicator application is pointing to v5.5, please follow the below procedure to resolve the issue 
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App(App Service) --> Go to Deployment Center --> Click on SYNC

- Once the status shows successful within logs section of Deployment Center.
<img width="833" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/9eb1d9a7-02f0-4583-8cd5-6f257eaa9ba8">

 
**Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service 
 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6e5045cb-27de-4e4f-9d22-7a7ef300888a)


- Please go to the Overview Section from and restart the app service.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6bb3fe8e-dbf2-4763-98f8-730460dd556d)

- Try accessing the CC application on Teams web client to avoid any cache related issue.

- If current deployed version of the Company Communicator application is pointing to v5.4.1 or previous versions, please upgrade your app to latest version by following the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide) as the fix is pushed to the main branch in Company Communicator's GitHub repo.

 
Please let us know if you are still facing the issue.

**Comment by HealthyGranty** [comment]
Thanks for the update. We are on a previous version, we have plans to upgrade to an upcoming version, so will factor into our plans. Thanks for the update, happy for this to be marked resolved/completed.
