### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ahlim0011** [OfficeDev/microsoft-teams-apps-company-communicator#1218]

**Comment by gsv022** [comment]
Hi @ahlim0011 ,
Thank you for reaching out to us, this issue started happening intermittently since 1st week of November, we're working with internal teams to identify the root cause of the issue. Please note that there has been no changes made in the Company Communicator code base, it seems to be an issue with one of the dependent services. 

We'll keep you posted with updates on the issue, sorry for any inconvenience caused.

**Comment by spiritgolfer** [comment]
Hi,

We just had this issue happen as well.  However, this issue is only on the new version of MS Teams.  If I switch back to classic MS Teams, CC still works.  There must be a difference in the code between the two versions on how they interact with 3rd party apps.
Try it and see!

**Comment by ahlim0011** [comment]
are you able to help me? I still have the same issue, sorry to ask but maybe we can have a teams call

**Comment by gsv022** [comment]
Hi @ahlim0011 ,
Thank you for the patience. 

- The app service authentication issue is now resolved, and the changes have been pushed to Company Communicator GitHub repository. 

- If current version of the Company Communicator application is pointing to v5.5, please follow the below procedure to resolve the issue 
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App(App Service) --> Go to Deployment Center --> Click on SYNC

- Once the status shows successful within logs section of Deployment Center.
<img width="833" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/9eb1d9a7-02f0-4583-8cd5-6f257eaa9ba8">

 
**Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service 
 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6e5045cb-27de-4e4f-9d22-7a7ef300888a)


- Please go to the Overview Section from and restart the app service.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6bb3fe8e-dbf2-4763-98f8-730460dd556d)

- Try accessing the CC application on Teams web client to avoid any cache related issue.

- If current deployed version of the Company Communicator application is pointing to v5.4.1 or previous versions, please upgrade your app to latest version by following the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide) as the fix is pushed to the main branch in Company Communicator's GitHub repo.

 
Please let us know if you are still facing the issue.

**Comment by dmmw2m** [comment]
> Hi @ahlim0011 , Thank you for the patience.
> 
> * The app service authentication issue is now resolved, and the changes have been pushed to Company Communicator GitHub repository.
> * If current version of the Company Communicator application is pointing to v5.5, please follow the below procedure to resolve the issue
>   Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App(App Service) --> Go to Deployment Center --> Click on SYNC
> * Once the status shows successful within logs section of Deployment Center.
> 
> <img alt="image" width="833" src="https://user-images.githubusercontent.com/98143492/285200025-9eb1d9a7-02f0-4583-8cd5-6f257eaa9ba8.png">
> **Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service
> 
> ![image](https://user-images.githubusercontent.com/98143492/285199618-6e5045cb-27de-4e4f-9d22-7a7ef300888a.png)
> 
> * Please go to the Overview Section from and restart the app service.
>   ![image](https://user-images.githubusercontent.com/98143492/285199692-6bb3fe8e-dbf2-4763-98f8-730460dd556d.png)
> * Try accessing the CC application on Teams web client to avoid any cache related issue.
> * If current deployed version of the Company Communicator application is pointing to v5.4.1 or previous versions, please upgrade your app to latest version by following the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide) as the fix is pushed to the main branch in Company Communicator's GitHub repo.
> 
> Please let us know if you are still facing the issue.

my issue was solved with this last hot-fix. thanks
