### ISSUE TITLE
Company communicator app error

### ISSUE THREAD

**Issue by pmkinyua** [OfficeDev/microsoft-teams-apps-company-communicator#1227]
Hi,

I have been using company communicator, but recently I started getting this error from Team.

**_"Sorry, an error occured while trying to access this service"_**

We have recently upgraded to the new Teams. Could this be the cause?

**Comment by gsv022** [comment]
Hi @pmkinyua ,
Thank you for reaching out to us, this issue started happening intermittently since 1st week of November, we're working with internal teams to identify the root cause of the issue. Please note that there has been no changes made in the Company Communicator code base, it seems to be an issue with one of the dependent services. We'll keep you posted with updates on the issue, sorry for any inconvenience caused.

**Comment by gsv022** [comment]
Hi @pmkinyua ,
Thank you for the patience. 

- The app service authentication issue is now resolved, and the changes have been pushed to Company Communicator GitHub repository. 

- If current version of the Company Communicator application is pointing to v5.5, please follow the below procedure to resolve the issue 
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App(App Service) --> Go to Deployment Center --> Click on SYNC

- Once the status shows successful within logs section of Deployment Center.
<img width="833" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/9eb1d9a7-02f0-4583-8cd5-6f257eaa9ba8">

 
**Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service 
 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6e5045cb-27de-4e4f-9d22-7a7ef300888a)


- Please go to the Overview Section from and restart the app service.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6bb3fe8e-dbf2-4763-98f8-730460dd556d)

- Try accessing the CC application on Teams web client to avoid any cache related issue.

- If current deployed version of the Company Communicator application is pointing to v5.4.1 or previous versions, please upgrade your app to latest version by following the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide) as the fix is pushed to the main branch in Company Communicator's GitHub repo.

 
Please let us know if you are still facing the issue.

**Comment by pmkinyua** [comment]
Thanks, I shall embark on the upgrade and keep you posted.






Peter Kinyua

IT Systems Manager



M-KOPA | ***@***.*** | +254 723 511 347

[cid:28922870-7e4b-44af-b494-eea227d29999]

________________________________

**Comment by SynHam** [comment]
> Hi @pmkinyua , Thank you for the patience.
> 
> * The app service authentication issue is now resolved, and the changes have been pushed to Company Communicator GitHub repository.
> * If current version of the Company Communicator application is pointing to v5.5, please follow the below procedure to resolve the issue
>   Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App(App Service) --> Go to Deployment Center --> Click on SYNC
> * Once the status shows successful within logs section of Deployment Center.
> 
> <img alt="image" width="833" src="https://user-images.githubusercontent.com/98143492/285200025-9eb1d9a7-02f0-4583-8cd5-6f257eaa9ba8.png">
> **Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service
> 
> ![image](https://user-images.githubusercontent.com/98143492/285199618-6e5045cb-27de-4e4f-9d22-7a7ef300888a.png)
> 
> * Please go to the Overview Section from and restart the app service.
>   ![image](https://user-images.githubusercontent.com/98143492/285199692-6bb3fe8e-dbf2-4763-98f8-730460dd556d.png)
> * Try accessing the CC application on Teams web client to avoid any cache related issue.
> * If current deployed version of the Company Communicator application is pointing to v5.4.1 or previous versions, please upgrade your app to latest version by following the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide) as the fix is pushed to the main branch in Company Communicator's GitHub repo.
> 
> Please let us know if you are still facing the issue.

Hi, i have updated our deployment. Seems to be opening in the webapp now, but I was trying to setup a test and send to a m365 group, but when i search it just clears itself out and shows no results. This is the same on classic and new Teams on the webapp.
The desktop app is still playing up at the moment.

**Comment by pmkinyua** [comment]
Hello

I have followed the guide for migrating from v4 and even tried a whole new deployment of the communicator app on a different subscription but I keep getting the below error.

{"code":"BadRequest","message":"There was a conflict. Conflict with existing ScmType: ExternalGit","details":[{"message":"There was a conflict. Conflict with existing ScmType: ExternalGit"},{"code":"BadRequest"},{}]}
<img width="855" alt="Screenshot 2023-11-27 132147" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151738749/a9b799b9-d9c8-4021-b2ba-73708cecdf45">

**Comment by gsv022** [comment]
Hi @pmkinyua ,
As you already deployed CC of latest version. To overcome the issue, please SYNC app service by following the provided steps.

> Hi,
> 
> I have been using company communicator, but recently I started getting this error from Team.
> 
> **_"Sorry, an error occured while trying to access this service"_**
> 
> We have recently upgraded to the new Teams. Could this be the cause?
