### ISSUE TITLE
Version of company communicator

### ISSUE THREAD

**Issue by ostromecko** [OfficeDev/microsoft-teams-apps-company-communicator#1240]
We have deployed before summer in our tenant the 5.4.1 version of CC. I have done sync in order to have the latest version. Where in Azure resource group for our application I can find and confirm which version we are using now?

**Comment by gsv022** [comment]
Hi @ostromecko ,
Thanks for raising the query. Here is procedure. 

- If current deployed version of the Company Communicator application is pointing to v5.4.1 or previous versions, please upgrade your app to latest version by following the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide) as the fix is pushed to the main branch in Company Communicator's GitHub repo.
- To check the version deployed,
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App(App Service) --> Go to Deployment Center-->Click on logs. Her is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/fd23ef37-8316-4aa4-bf4d-a37c3ba4a2ea)

**Comment by ostromecko** [comment]
here is the screenshot:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134921401/ba85b2b5-fc8e-4375-8dae-3a9f058a26ed)

**Comment by gsv022** [comment]
Hi @ostromecko ,
Currently you are on latest version. That can be confirmed by opening the commit ID. Then open logs, version of the application can be observed. Here is the reference.
<img width="493" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/33602edb-e46c-4ab1-ae6e-9c3070aac33a">

**Comment by ostromecko** [comment]
Hi @gsv022, I can notice only 5.4.1 version in the log. There is no mention about 5.5.

**Comment by gsv022** [comment]
Hi @ostromecko ,
To check the version.

- Depending on the commit id, the version can be found. Here is the [reference](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/commits/main)
- This is also one of the places where [version](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Frequently-Asked-Questions-(FAQ)#10-how-do-i-know-the-version-of-the-app) of the app can be found.
