### ISSUE TITLE
Error after new deployment - Sorry, an error occurred while trying to access this service.

### ISSUE THREAD

**Issue by spikedfuel** [OfficeDev/microsoft-teams-apps-company-communicator#1244]
After powershell deployment, everything was successful in the deploy, but getting an error when accessing:
![communicator_error](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/41805678/daff52e4-d925-4545-885c-f88b19de74a8)

Any suggested troubleshooting steps?

**Comment by gsv022** [comment]
Hi @spikedfuel ,

- The app service authentication issue is now resolved, and the changes have been pushed to Company Communicator GitHub repository. 

- If current version of the Company Communicator application is pointing to v5.5, please follow the below procedure to resolve the issue 
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App(App Service) --> Go to Deployment Center --> Click on SYNC

- Once the status shows successful within logs section of Deployment Center.
<img width="833" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/9eb1d9a7-02f0-4583-8cd5-6f257eaa9ba8">

 
**Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service 
 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6e5045cb-27de-4e4f-9d22-7a7ef300888a)


- Please go to the Overview Section from and restart the app service.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6bb3fe8e-dbf2-4763-98f8-730460dd556d)

- Try accessing the CC application on Teams web client to avoid any cache related issue.

- If current deployed version of the Company Communicator application is pointing to v5.4.1 or previous versions, please upgrade your app to latest version by following the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide) as the fix is pushed to the main branch in Company Communicator's GitHub repo.

 
Please let us know if you are still facing the issue.

**Comment by spikedfuel** [comment]
I did a sync @gsv022 and then uploaded the new app packages to Teams. Getting the following error when doing org consent:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/41805678/8fde2876-88bf-462f-a1b0-d3923df5199c)
checked app api permissions:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/41805678/faa7e556-82d8-4312-bb13-788a4fa77d8e)
(noted neither of the admin/user app registrations had any configured permissions)
enterprise app is consented:

**Comment by spikedfuel** [comment]
@gsv022 I was waiting on your response in regards to the Teams Admin console error with that latest package. "Please contact your tenant admin to fix the client application registration" - which I then sent the screenshots showing it is registered (at least where I assumed it needed to be) in the enterprise app registrations.

Despite the error, I was able to get the Company Communicator Admin to load, and a test message is queued....
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/41805678/5be3ac0d-81d7-4bff-ad0f-89ed3b4eaa26)

Seeing a ton of errors in the application insights:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/41805678/126399ed-585c-4dac-8a01-7457d80eabba)

Can we schedule a quick call?

**Comment by gsv022** [comment]
Hi @spikedfuel ,
Please cross verify the secrets. Here is the procedure for comparison. 

- Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault  from list of resources

- Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret.

**Comment by spikedfuel** [comment]
I've verified all the client secrets / keyvault are correct. I then attempted to sync the deployment via the deployment center and it fails to update. 

Failed exitCode=1, command=npm run build
An error has occurred during web site deployment.
npm WARN old lockfile \r\nnpm WARN old lockfile The package-lock.json file was created with an old version of npm,\r\nnpm WARN old lockfile so supplemental metadata must be fetched from the registry.\r\nnpm WARN old lockfile \r\nnpm WARN old lockfile This is a one-time fix-up, please be patient...\r\nnpm WARN old lockfile \r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.4.1\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-

**Comment by gsv022** [comment]
Hi @spikedfuel ,
There is a app service issue sync issue is going on. We are currently looking into it on priority. We will keep you posted

**Comment by spikedfuel** [comment]
any updates?

**Comment by gsv022** [comment]
Hi @spikedfuel ,
Thank you for the patience. The app service sync failure issue is now resolved, and the changes have been pushed to Company Communicator [official GitHub repository](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414961979%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JVcWd4Z3mUGCDkrlKJekbpry%2FUCEAQQ0iqfdfMqJgDs%3D&reserved=0). 

If current deployed version of the Company Communicator application is pointing to v5.5 (latest version), please follow the below procedure to resolve the issue -

- Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center --> Click on **SYNC**

- Once the status shows successful within logs section of Deployment Center.

<img width="611" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6b02124a-cd7b-4c37-872e-7b7136d277ec">


**Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d208800b-e1ca-4748-b065-8172ec18e49f)

- Try accessing the CC application on Teams web client to avoid any cache related issue.

If current deployed version of the Company Communicator application is pointing to **v5.4.1 or previous versions**, please upgrade your app to latest version by following the [migration guide](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fwiki%2Fv5-migration-guide&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414973282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vKt9QZgQYo%2FPt5r08uTTsx2bwdmbS2eBaJETCel%2B9vs%3D&reserved=0) as the fix is pushed to the **main** branch in Company Communicator's official GitHub repo.
If it’s a fresh deployment then proceed with the remaining steps as per the [deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide).
Please let us know if you are still facing the issue.

**Comment by spikedfuel** [comment]
Hi @gsv022  - ran the sync as requested, verified it was success (active) to #1280. Restarted webapp. Messages still queueing.
This is a brand new deployment, I verified the permissions previously for the keys to the app services. Errors in the app insight:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/41805678/cf65b002-a3f4-4cf2-bc8b-369ded520d31)

**Comment by gsv022** [comment]
Hi @spikedfuel ,
Please cross verify the secrets. Here is the procedure for comparison. 

- Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault  from list of resources

- Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret.

**Comment by spikedfuel** [comment]
I have three app registrations:
graph - confirmed the client secret matches  vaultGraphAppPassword secret value
authors - confirmed the client secret matches vaultAuthorAppPassword secret value
users - confirmed the client secret matches vaultUserAppPassword secret value

**Comment by gsv022** [comment]
Hi @spikedfuel ,
 Please cross-verify the set-up authentication [steps](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) present in deployment guide and share the relevant screenshots here.

**Comment by spikedfuel** [comment]
I'll check on this today, thanks Sai

**Comment by gsv022** [comment]
@spikedfuel 
Sure, Please keep us posted.
