### ISSUE TITLE
Messages are not being send from Company Communicator application .

### ISSUE THREAD

**Issue by AdnanMcit** [OfficeDev/microsoft-teams-apps-company-communicator#1252]
We have two custom applications named Mishaar and Company Communicator , both uploaded to the Teams Admin Center to make them accessible to every user in our organization. Mishaar is a web app service hosted in Azure, and it was recently migrated from the West Europe region to the Qatar Central region. However, since the migration and renaming, the application is experiencing functionality issues.When a user tries to send a message via Company  Communicator, the message is simultaneously visible in Mishaar However, when it comes to receiving the messages, is from Company Communicator, there are instances where other users are not receiving the messages.

•	Messages are not being sent to some users from Company Communicator app.
•	Messages are being sent to only 2-3 users out 20.
•	It was working as expected before.
•	But after renaming "QC communicator" author App to "Mishaar" this issue is coming.

Your prompt help is required concerning this matter.

**Comment by AdnanMcit** [comment]
Hello Sai,

Thank you for your response .

I have attached the deployment status snips of the app service to this email .

Currently Application insights is not enabled for this app service.

Thanks & regards,
Adnan



Classified_Internal

Adnan Mohammed Iqbal​​​​
System Administrator
***@***.******@***.***>
***@***.***
***@***.***
www.mcit.gov.qa<http://www.mcit.gov.qa/>
***@***.***
البريد مقابل ، ب النصر برج
الكورنيش شارع
***@***.***
Al Nassr Tower B,
Corniche St., Doha

***@***.***

إخلاء المسؤولية: محتوى هذا البريد الإلكتروني سري ومخصص للمستلم المحدد في الرسالة فقط. يمنع منعا باتا مشاركة أي جزء من هذه الرسالة مع أي طرف ثالث ، دون موافقة خطية من المرسل. إذا تلقيت هذه الرسالة عن طريق الخطأ ، فالرجاء الرد  على هذه الرسالة والمتابعة بحذفها ، حتى نتمكن من ضمان عدم حدوث مثل هذا الخطأ في المستقبل
​
Disclaimer:The content of this email is confidential and intended for the recipient specified in the message only. It is strictly forbidden to share any part of this message with any third party, without written consent from the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.




Classified_Internal

**Comment by gsv022** [comment]
@AdnanMcit , Please send the snippets of app service deployment status here only.

**Comment by AdnanMcit** [comment]
Hello,

I have responded to your engineer, Sai Venkat, with the requested details. Please designate this case as active.
@Sai ***@***.***>
Thanks & regards,
Adnan



Classified_Internal

Adnan Mohammed Iqbal​
System Administrator
***@***.******@***.***>
***@***.***
***@***.***
www.mcit.gov.qa<http://www.mcit.gov.qa/>
***@***.***
البريد مقابل ، ب النصر برج
الكورنيش شارع
***@***.***
Al Nassr Tower B,
Corniche St., Doha

***@***.***

إخلاء المسؤولية: محتوى هذا البريد الإلكتروني سري ومخصص للمستلم المحدد في الرسالة فقط. يمنع منعا باتا مشاركة أي جزء من هذه الرسالة مع أي طرف ثالث ، دون موافقة خطية من المرسل. إذا تلقيت هذه الرسالة عن طريق الخطأ ، فالرجاء الرد  على هذه الرسالة والمتابعة بحذفها ، حتى نتمكن من ضمان عدم حدوث مثل هذا الخطأ في المستقبل
​
Disclaimer:The content of this email is confidential and intended for the recipient specified in the message only. It is strictly forbidden to share any part of this message with any third party, without written consent from the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.




Classified_Internal

**Comment by gsv022** [comment]
Hi @AdnanMcit ,
Please share the screenshots here only. Even in the mail it is coming in masked state.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/b1d3a0b9-1091-4381-84e3-8e299b51b00b)

**Comment by gsv022** [comment]
Hi @AdnanMcit ,
Thank you for the patience. The app service sync failure issue is now resolved, and the changes have been pushed to Company Communicator [official GitHub repository](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414961979%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JVcWd4Z3mUGCDkrlKJekbpry%2FUCEAQQ0iqfdfMqJgDs%3D&reserved=0). 

If current deployed version of the Company Communicator application is pointing to v5.5 (latest version), please follow the below procedure to resolve the issue -

- Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center --> Click on **SYNC**

- Once the status shows successful within logs section of Deployment Center.

<img width="611" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6b02124a-cd7b-4c37-872e-7b7136d277ec">


**Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d208800b-e1ca-4748-b065-8172ec18e49f)

- Try accessing the CC application on Teams web client to avoid any cache related issue.

If current deployed version of the Company Communicator application is pointing to **v5.4.1 or previous versions**, please upgrade your app to latest version by following the [migration guide](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fwiki%2Fv5-migration-guide&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414973282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vKt9QZgQYo%2FPt5r08uTTsx2bwdmbS2eBaJETCel%2B9vs%3D&reserved=0) as the fix is pushed to the **main** branch in Company Communicator's official GitHub repo.
If it’s a fresh deployment then proceed with the remaining steps as per the [deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide).
Please let us know if you are still facing the issue.
