### ISSUE TITLE
Error al intentar sincronizar 

### ISSUE THREAD

**Issue by dmedina1520** [OfficeDev/microsoft-teams-apps-company-communicator#1262]
Cuando intentamos sincronizar la nos sale este error:
<img width="712" alt="errorwebapp" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/153597322/f4ba1236-84cb-4813-90cb-f8ceabbd2fc9">

Hemos realizado los pasos correspondientes que indicáis en este sitio: https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#2-validate-and-update-the-config-settings-and-sync-to-the-lastest-code-

**Comment by gsv022** [comment]
Hi @dmedina1520 ,
Thanks for raising the query. 

- What is the app service plan here?
- Please disconnect the repository within settings and give some time gap and then connect to the repository again

**Comment by dmedina1520** [comment]
Cuanto mas o menos, ayer lo hice y lo deje durante 30 min y despues lo volvi a poner y no funciono pero lo vuelvo hacer hoy

**Comment by dmedina1520** [comment]
Aqui te paso la app service:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/153597322/6f009ba2-2d1e-4a40-9828-de4379bdfcea)

**Comment by dmedina1520** [comment]
Hemos desconectado el repositorio durante 24 horas y sigue con el mismo fallo.
<img width="582" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/153597322/8c12dc81-360c-40cc-a507-e6acaecb14fe">

**Comment by gsv022** [comment]
Hi @dmedina1520 ,
Thank you for the patience. The app service sync failure issue is now resolved, and the changes have been pushed to Company Communicator [official GitHub repository](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414961979%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JVcWd4Z3mUGCDkrlKJekbpry%2FUCEAQQ0iqfdfMqJgDs%3D&reserved=0). 

If current deployed version of the Company Communicator application is pointing to v5.5 (latest version), please follow the below procedure to resolve the issue -

- Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center --> Click on **SYNC**

- Once the status shows successful within logs section of Deployment Center.

<img width="611" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6b02124a-cd7b-4c37-872e-7b7136d277ec">


**Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d208800b-e1ca-4748-b065-8172ec18e49f)

- Try accessing the CC application on Teams web client to avoid any cache related issue.

If current deployed version of the Company Communicator application is pointing to **v5.4.1 or previous versions**, please upgrade your app to latest version by following the [migration guide](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fwiki%2Fv5-migration-guide&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414973282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vKt9QZgQYo%2FPt5r08uTTsx2bwdmbS2eBaJETCel%2B9vs%3D&reserved=0) as the fix is pushed to the **main** branch in Company Communicator's official GitHub repo.
If it’s a fresh deployment then proceed with the remaining steps as per the [deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide).
Please let us know if you are still facing the issue.

**Comment by dmedina1520** [comment]
Ahora el error es otro 
<img width="507" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/153597322/bf17d9d6-8498-4829-8ef4-21149c71323d">

**Comment by gsv022** [comment]
Hi @dmedina1520 ,
Please disconnect  the repository, wait for sometime to delete the existing repository. Then connect again to main branch of official repo. Please do share the mail id(outlook id or teams id) If it fails again, we can connect.

**Comment by casticod2** [comment]
Hola, soy compañero de trabajo de Dmedina1520, el se encuentra ausente.. 
Hemos seguido instrucciones dadas, desconectado repositorio, esperado 12 horas, vuelto a reconectar y el error es otro.. 
![imagen (3)](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/90576784/8e19202f-6b00-4e76-a51d-afe641d06e59)
![imagen (2)](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/90576784/c818ac61-1606-4616-a5d5-259c099a4109)
![imagen (4)](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/90576784/a77e2967-d9b8-47e1-88fc-b9e287bb2e75)

**Comment by dmedina1520** [comment]
Ahora directamente te sale el error, no intenta ni sincronizar
<img width="695" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/153597322/7a76d2f0-fa01-4b60-97de-b7ca7508001a">

**Comment by gsv022** [comment]
Hi @dmedina1520 
Please translate it to English so that we can assist you in a better way.

**Comment by dmedina1520** [comment]
Now you get the error directly, don't even try to synchronize

**Comment by dmedina1520** [comment]
There's something new about the bug

**Comment by gsv022** [comment]
Hi @dmedina1520 ,
Please let us know if you are still facing the issue.
