### ISSUE TITLE
Issue with ResourceDeploymentFailure

### ISSUE THREAD

**Issue by jkicyjet** [OfficeDev/microsoft-teams-apps-company-communicator#1263]
Hi, 

I have issue when try to deploy new the app.
Refer as attached, even try to sync again still failed. please advise how can I do on this.
I tried to deploy for 10 times already but it keep failed this message.

error "message": "The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'."
![error1](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150225179/76d705b7-c82e-4a3d-b6a8-215b95a2ec23)

![syncerror](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150225179/5bb75c7d-87fb-40b1-971a-813e33d003b7)

**Comment by gsv022** [comment]
Hi @jkicyjet ,
Thanks for raising the query. We will check it out from our side and keep you posted

**Comment by gsv022** [comment]
Hi @jkicyjet ,
Thank you for the patience. The app service sync failure issue is now resolved, and the changes have been pushed to Company Communicator [official GitHub repository](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414961979%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JVcWd4Z3mUGCDkrlKJekbpry%2FUCEAQQ0iqfdfMqJgDs%3D&reserved=0). 

If current deployed version of the Company Communicator application is pointing to v5.5 (latest version), please follow the below procedure to resolve the issue -

- Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center --> Click on **SYNC**

- Once the status shows successful within logs section of Deployment Center.

<img width="611" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6b02124a-cd7b-4c37-872e-7b7136d277ec">


**Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d208800b-e1ca-4748-b065-8172ec18e49f)

- Try accessing the CC application on Teams web client to avoid any cache related issue.

If current deployed version of the Company Communicator application is pointing to **v5.4.1 or previous versions**, please upgrade your app to latest version by following the [migration guide](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fwiki%2Fv5-migration-guide&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414973282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vKt9QZgQYo%2FPt5r08uTTsx2bwdmbS2eBaJETCel%2B9vs%3D&reserved=0) as the fix is pushed to the **main** branch in Company Communicator's official GitHub repo.
If it’s a fresh deployment then proceed with the remaining steps as per the [deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide).
Please let us know if you are still facing the issue.
