### ISSUE TITLE
Failed to compile while performing Sync on Web App\App Service

### ISSUE THREAD

**Issue by HamzaCeranic** [OfficeDev/microsoft-teams-apps-company-communicator#1265]
When trying to perform the Sync and get the newest version deployed I get this error:
Failed to compile.

TS2322: Type '{ children: string[]; style: { gridColumn: "2"; marginLeft: string; marginRight: string; paddingTop: string; color: "darkgray"; }; placeholder: string; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Property 'placeholder' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
    783 |                       color: 'darkgray',
    784 |                     }}
  > 785 |                     placeholder="{t('FieldSeperator')}"
        |                     ^^^^^^^^^^^
    786 |                   >
    787 |                     {' '}
    788 |                     (Or){' '}

Failed exitCode=1, command=npm run build
An error has occurred during web site deployment.

**Comment by gojo119** [comment]
I have the same problem when running a sync.

**Comment by HamzaCeranic** [comment]
Seems to be the same Problem as this Error al intentar sincronizar #1262
I have tried disconnecting and reconnecting the Repository. It is still the same. 
Here is the App Subscription Plan. 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/153643365/ece8dd1f-5927-4ec4-8da7-489e6ba288ac)

**Comment by gsv022** [comment]
Hi @HamzaCeranic ,
Thanks for raising the query. We are looking into the issue on priority and keep you posted

**Comment by gsv022** [comment]
Hi @HamzaCeranic ,
Thank you for the patience. The app service sync failure issue is now resolved, and the changes have been pushed to Company Communicator [official GitHub repository](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414961979%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JVcWd4Z3mUGCDkrlKJekbpry%2FUCEAQQ0iqfdfMqJgDs%3D&reserved=0). 

If current deployed version of the Company Communicator application is pointing to v5.5 (latest version), please follow the below procedure to resolve the issue -

- Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center --> Click on **SYNC**

- Once the status shows successful within logs section of Deployment Center.

<img width="611" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6b02124a-cd7b-4c37-872e-7b7136d277ec">


**Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d208800b-e1ca-4748-b065-8172ec18e49f)

- Try accessing the CC application on Teams web client to avoid any cache related issue.

If current deployed version of the Company Communicator application is pointing to **v5.4.1 or previous versions**, please upgrade your app to latest version by following the [migration guide](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fwiki%2Fv5-migration-guide&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414973282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vKt9QZgQYo%2FPt5r08uTTsx2bwdmbS2eBaJETCel%2B9vs%3D&reserved=0) as the fix is pushed to the **main** branch in Company Communicator's official GitHub repo.
If it’s a fresh deployment then proceed with the remaining steps as per the [deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide).
Please let us know if you are still facing the issue.
