### ISSUE TITLE
Mgmt.AppCatalog.LOBApp.Upload.BadRequest.Error

### ISSUE THREAD

**Issue by sudheeshrajan1** [OfficeDev/microsoft-teams-apps-company-communicator#1272]
I am getting an error"Mgmt.AppCatalog.LOBApp.Upload.BadRequest.Error" while uploading the company communicator author app and user app under teams after the deployment in Azure.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/153543509/bdd233f0-50e4-4b6a-9ec0-786e5b64a93f)

Any lead on this issue ?

Thanks,

Sudheesh Rajan

**Comment by marcelojrm** [comment]
Try sending the 3 files inside the zip, without any folder inside the zip.

**Comment by sudheeshrajan1** [comment]
Please find the files.

**Comment by gsv022** [comment]
Hi @sudheeshrajan1 ,
Thanks for raising the query. Please share the zipped manifest files.

**Comment by sudheeshrajan1** [comment]
Hi Sai,

I have already shared, sharing again.

Thanks,

Sudheesh Rajan

**Comment by sudheeshrajan1** [comment]
[Company communicator authors.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/13702698/Company.communicator.authors.zip)
[Users.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/13702704/Users.zip)

**Comment by sudheeshrajan1** [comment]
Any insight on this please?

**Comment by gsv022** [comment]
@sudheeshrajan1 ,Please Update the URL's in the manifest files and zip it again. It will work.
<img width="392" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/314680f2-74ff-432f-8969-e09bbe1a02a1">

**Comment by sudheeshrajan1** [comment]
Looks like it is coming from the configuration url, I could see it is running. Any help on this please ?

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/153543509/97931284-2afb-4345-a6e9-97037375970e)

**Comment by gsv022** [comment]
Hi @sudheeshrajan1 ,
- Please share the deployment status of App service. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/5f09116e-4605-4d29-84cc-c6e690fb13d5)


![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/8fad1fcd-30a4-4658-bc32-1c9fd333a45c)

**Comment by sudheeshrajan1** [comment]
Please find the screenshot

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/153543509/62aeb784-f3a9-4b23-b6c2-e60cd9a22e70)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/153543509/f4f34213-e13c-4f6f-805b-e8484a1b0150)

**Comment by sudheeshrajan1** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/153543509/fd35c695-cab8-4b01-acc6-84abbd64678c)

**Comment by sudheeshrajan1** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/153543509/2d904ba9-2f2a-4249-8274-98ec270a9176)

**Comment by gsv022** [comment]
Hi @sudheeshrajan1 ,
Thank you for the patience. The app service sync failure issue is now resolved, and the changes have been pushed to Company Communicator [official GitHub repository](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414961979%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JVcWd4Z3mUGCDkrlKJekbpry%2FUCEAQQ0iqfdfMqJgDs%3D&reserved=0). 

If current deployed version of the Company Communicator application is pointing to v5.5 (latest version), please follow the below procedure to resolve the issue -

- Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center --> Click on **SYNC**

- Once the status shows successful within logs section of Deployment Center.

<img width="611" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6b02124a-cd7b-4c37-872e-7b7136d277ec">


**Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d208800b-e1ca-4748-b065-8172ec18e49f)

- Try accessing the CC application on Teams web client to avoid any cache related issue.

If current deployed version of the Company Communicator application is pointing to **v5.4.1 or previous versions**, please upgrade your app to latest version by following the [migration guide](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fwiki%2Fv5-migration-guide&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414973282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vKt9QZgQYo%2FPt5r08uTTsx2bwdmbS2eBaJETCel%2B9vs%3D&reserved=0) as the fix is pushed to the **main** branch in Company Communicator's official GitHub repo.
If it’s a fresh deployment then proceed with the remaining steps as per the [deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide).
Please let us know if you are still facing the issue.
