### ISSUE TITLE
Company Communicator - "An error occured" and "You don't have permission"

### ISSUE THREAD

**Issue by silva1512** [OfficeDev/microsoft-teams-apps-company-communicator#1274]
I'm facing 2 errors with Company Communitor on Teams.

Teams Desktop App - "Sorry, you don't have permission to access this page. Contact the administrator to receive permission."

Teams Web App - "An error occured while trying to access this service."

I'm attaching the screenshots.

I was looking at the others Issues posted here, I understood that I must configure via Azure to Sync to another URL.
I've done that but the error is still occuring. I attached the screenshot so you guys can see if I've done anything wrong.
![Teams-desktop](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154267052/5fe33615-06e0-4048-a9d8-91f205b4df3d)
![Teams-web](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154267052/33bc9ed6-dcef-49a8-9c34-100d15e2cac5)
![azure-view](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154267052/b2cde960-31dc-4992-b560-6b80d2677d29)

**Comment by gsv022** [comment]
Hi @silva1512 ,
Thanks for raising the query. Please confirm on the below point.
 
-" _I've done that but the error is still occurring"._ as you said, please mention the steps performed.

**Comment by silva1512** [comment]
here it is

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1244#issuecomment-1835498617

**Comment by gsv022** [comment]
Hi @silva1512 ,
Thank you for raising the query. The app service sync failure issue is now resolved, and the changes have been pushed to Company Communicator [official GitHub repository](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414961979%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JVcWd4Z3mUGCDkrlKJekbpry%2FUCEAQQ0iqfdfMqJgDs%3D&reserved=0). 

If current deployed version of the Company Communicator application is pointing to v5.5 (latest version), please follow the below procedure to resolve the issue -

- Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center --> Click on **SYNC**

- Once the status shows successful within logs section of Deployment Center.

<img width="611" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6b02124a-cd7b-4c37-872e-7b7136d277ec">


**Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d208800b-e1ca-4748-b065-8172ec18e49f)

- Try accessing the CC application on Teams web client to avoid any cache related issue.

If current deployed version of the Company Communicator application is pointing to **v5.4.1 or previous versions**, please upgrade your app to latest version by following the [migration guide](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fwiki%2Fv5-migration-guide&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414973282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vKt9QZgQYo%2FPt5r08uTTsx2bwdmbS2eBaJETCel%2B9vs%3D&reserved=0) as the fix is pushed to the **main** branch in Company Communicator's official GitHub repo.
If it’s a fresh deployment then proceed with the remaining steps as per the [deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide).
Please let us know if you are still facing the issue.

**Comment by silva1512** [comment]
"If current deployed version of the Company Communicator application is pointing to v5.5 (latest version)"
Where can I check this?

**Comment by silva1512** [comment]
Hello gsv022,
Thank you for the information provided.

I was able to check and we're currently running the version 5.1.0

**Comment by silva1512** [comment]
Well, I followed the procedure you sent me but had no success.
I'm attaching the logs. I believe there's something that is preventing the app to be updated.
As you can see, it shows that a log from June 14, 2022 is still trying to deploy something...
Also, I'm attaching another error that is appearing for us, I believe it's related to the version being 5.1.0
![log-01](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154267052/1e91aaa1-2eaf-43d2-88f3-f9c2c64fb15b)
![log-02](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154267052/40008b87-48ee-4552-8bcc-8468ab7d300b)
![log-03](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154267052/90c0c1b8-23d2-43ba-bf71-5051a95a6b84)

**Comment by gsv022** [comment]
Hi @silva1512 ,
Since you are on v5.1.0, please perform migration steps as per the [guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v5x-to-latest-version). If performed already, please share the screenshot as shown in the migration guide for function apps and app service

**Comment by silva1512** [comment]
Alright,
I already followed the guide, you sent me in the other reply.
I understood that this v5.1.0 is the one being "redeployed" and when I try to fetch the v5.5 it shows an error.
So, it seems like it is "stuck" at v5.1.0...
Do you know where I can look at this "Diagnostic Logs" ? 
![fetch-error](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154267052/2e965ecd-42aa-4646-b539-a46b489b4f06)
![diag-log](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154267052/905a7c39-2ac2-44d3-ab5d-de67766c5240)

**Comment by silva1512** [comment]
As you can see, whenever I try to sync it starts to run the deployment from v5.1.0, i don't know why...

![run-deploy-error](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154267052/0441871b-66cf-4374-9276-718eeb445b27)

**Comment by gsv022** [comment]
Hi @silva1512 ,
Currently you are in the logs section of app service, switch to settings in the same page. Then disconnect and connect the repository pointing to main branch. After that check the deployment status in the logs section of deployment center. Do the same for all resources(data-function, send function, prep-function)

**Comment by silva1512** [comment]
Hi @gsv022 ,
Thank you for your help.
I was able to update to version 5.5 and this error has been solved.
Unfortunately, another error appeared, but since the main error was solved, i'll create a separate issue for the other one.
I solved by disconnecting and connecting the external source - Git.
I appreciate your help! Thanks again.
