### ISSUE TITLE
Company communicator re installation

### ISSUE THREAD

**Issue by ManasaMShastri** [OfficeDev/microsoft-teams-apps-company-communicator#1309]
Hi,

We already have one company communicator in our tenant and we need another app so kindly confirm the steps to follow to create a new deployment of company communicator.

**Comment by gsv022** [comment]
Hi @ManasaMShastri ,
Thanks for raising the query.  

- _We need another app so kindly confirm the steps to follow to create a new deployment of company communicator._
Within a tenant, there can be more than one instance of CC. The necessary steps needed to be taken care are

1. During ARM template filling, the parameter **UserAppExternal ID**- Update with new valid GUID. Because with the below GUID old user app should have been utilized already.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d6f2d232-0857-43c7-995c-1f122fa0ee24)

2. Please make sure to update below place in the user-manifest with the above newly generated GUID(used for UserAppExternal ID)before uploading to the tenant
<img width="762" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/8d354bce-cea6-44cc-b8a1-944ac0532d4b">

3. For the author app, below is the only place that need to be updated with new valid GUID and then upload.
<img width="452" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/5b86c5dc-5811-4c75-8317-999379024f81">

4. It is good to have a different names for each instance of CC.

**Note:** Avoid having two instances of CC within same team. It may create ambiguity.

**Comment by ManasaMShastri** [comment]
Kindly confirm from where we will get the UserAppExternal ID.

**Comment by gsv022** [comment]
@ManasaMShastri, Here is the [link](https://www.guidgenerator.com/online-guid-generator.aspx) to generate GUID's

**Comment by ManasaMShastri** [comment]
Thank you!!

We have successfully created the app but we are getting the following errors kindly suggest
![image (3)](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/148181089/8716fe4c-5cc6-41d3-8289-d1231788b583)

**Comment by gsv022** [comment]
Hi @ManasaMShastri ,
Please go for re-deploy and then if again any resources such as function/prep-function/data-function/web(app service)  got failed. Perform the below procedure.

- To overcome the failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select **prep-function** from list of resources-->Go to Deployment Center-->Click on Settings. Below is the screenshot for reference. 

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- If the resource is not pointing to intended repository and  showing empty. Please connect to the external Git and point to the official repository(like above)
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.
- Please do the same for other failed resource as well.
- After performing the above steps, don't attempt for re-deploy again
