### ISSUE TITLE
Unexpected error occurs when author users try to view a detailed report.

### ISSUE THREAD

**Issue by Camboya466** [OfficeDev/microsoft-teams-apps-company-communicator#1318]
Last year, we implemented "Company Communicator" within the organization with the support of Microsoft. However, since that moment, we have been experiencing issues with the data report generated by this tool. To date, it has not been possible to generate the report and track the data from this channel, which has had a significant impact on our communications.
![aaa](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122912317/fcc9e8bc-1e53-437c-aff0-fd286704e4b9)

**Comment by gsv022** [comment]
Hi @Camboya466 ,
Thanks for raising the query. Could you please confirm on the below points.

- Are you able to deliver the message through all sending options?
- When was the migration performed to get updated to the latest version?
- Could you please share the deployment status of app service. Here is the reference.
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center --> Click on Logs. 

<img width="611" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6b02124a-cd7b-4c37-872e-7b7136d277ec">

**Comment by Camboya466** [comment]
Are you able to deliver the message through all sending options?
Yes, Company Communicator is woking fine.

When was the migration performed to get updated to the latest version?
Currently, I have installed 5.4.1 version

Could you please share the deployment status of app service. Here is the reference.
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center --> Click on Logs.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122912317/41ae5ba3-ba02-4359-995c-872af77fb593)

**Comment by gsv022** [comment]
Hi @Camboya466 ,
There was an app service sync issue that got resolved recently. Please go through the below steps. 
If current deployed version of the Company Communicator application is pointing to v5.5 (latest version), please follow the below procedure to resolve the issue -

- Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center --> Click on **SYNC**

- Once the status shows successful within logs section of Deployment Center.

<img width="611" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6b02124a-cd7b-4c37-872e-7b7136d277ec">


**Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/aacc8d3c-f128-472c-97ff-6ccd6288cf81)

- Please go to the Overview Section and restart the app service.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d208800b-e1ca-4748-b065-8172ec18e49f)

- Try accessing the CC application on Teams web client to avoid any cache related issue.

If current deployed version of the Company Communicator application is pointing to **v5.4.1 or previous versions**, please upgrade your app to latest version by following the [migration guide](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fwiki%2Fv5-migration-guide&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414973282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vKt9QZgQYo%2FPt5r08uTTsx2bwdmbS2eBaJETCel%2B9vs%3D&reserved=0) as the fix is pushed to the **main** branch in Company Communicator's official GitHub repo.
If it’s a fresh deployment then proceed with the remaining steps as per the [deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide).
Please let us know if you are still facing the issue.

**Comment by Camboya466** [comment]
Thanks for your answer.

I updated the web app and the button for export the results was enabled, however when I try to donwload the reports the app show error:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122912317/181af1e1-2f64-4dca-890f-f79d0e4c4771)

The applicaction is created in the tenant whit admin consent enabled.

**Comment by gsv022** [comment]
Please check the tenant id used in app service configuration is correct or not.

**Comment by Camboya466** [comment]
Hi, the AzureAd:TenantId is correct in the conf tab.

**Comment by gsv022** [comment]
Hi @Camboya466 ,
Could you please check whether your id is part of sender UPN list. 
<img width="902" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/4a9a9ffa-4a78-4d93-b3ae-23b6e9ce99df">

**Comment by Camboya466** [comment]
Hi, @gsv022 
I checked the variable, my UPN is part of sender UPN list.

**Comment by gsv022** [comment]
Hi @Camboya466 ,
Please cross-verify once again whether 1st and 2nd step present in [migration guide](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fwiki%2Fv5-migration-guide&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414973282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vKt9QZgQYo%2FPt5r08uTTsx2bwdmbS2eBaJETCel%2B9vs%3D&reserved=0)  are performed or not.
