### ISSUE TITLE
Error message in Company Communicator Author with the New Teams version desktop and web

### ISSUE THREAD

**Issue by SANCOR1** [OfficeDev/microsoft-teams-apps-company-communicator#1326]
When you access the new Teams and try to access the Company Communicator Author, an error is generated. This happens in the desktop and web version.

![Error Company Communicator Author in New Teams](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/42454632/005866fe-3dda-4403-8353-a4b035da9254)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/42454632/cc8a6cf7-dfc6-4563-97d8-d926e3e95804)

We are now working with this version: Version 5.1.1 Could you please help us solve this problem?

Thank you!

**Comment by wsp174212** [comment]
We encountered the same issue in "new teams" , please give some advice why the error occurs.

**Comment by gsv022** [comment]
Hi @SANCOR1 ,
Thanks for raising the query. The app service sync failure issue is now resolved, and the changes have been pushed to Company Communicator [official GitHub repository](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414961979%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JVcWd4Z3mUGCDkrlKJekbpry%2FUCEAQQ0iqfdfMqJgDs%3D&reserved=0). 

If current deployed version of the Company Communicator application is pointing to v5.5 (latest version), please follow the below procedure to resolve the issue -

- Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center --> Click on **SYNC**

- Once the status shows successful within logs section of Deployment Center.

<img width="611" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6b02124a-cd7b-4c37-872e-7b7136d277ec">


**Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/30963757-1db6-448a-b4ba-1f7ef1cbf6e0)

- please go to the Overview Section and restart the app service.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d208800b-e1ca-4748-b065-8172ec18e49f)

- Try accessing the CC application on Teams web client to avoid any cache related issue.

If current deployed version of the Company Communicator application is pointing to **v5.4.1 or previous versions**, please upgrade your app to latest version by following the [migration guide](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fwiki%2Fv5-migration-guide&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414973282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vKt9QZgQYo%2FPt5r08uTTsx2bwdmbS2eBaJETCel%2B9vs%3D&reserved=0) as the fix is pushed to the **main** branch in Company Communicator's official GitHub repo.
If it’s a fresh deployment then proceed with the remaining steps as per the [deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide).
Please let us know if you are still facing the issue.

**Comment by srojas1591** [comment]
Hello @gsv022 I do have the same issue and followed the steps to solve this and the issue still persists... is there any workaround?? Or can you help us to solve this 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/39104462/10d1d1d8-02c4-4591-9779-3b1bd5313fd0)

**Comment by SharlenePollock** [comment]
We also have this issue in new Teams. We are on version 5.0.1 but I'm assuming it's a Teams issue not a version issue. Would really like to know if there's a way to resolve it before MS removes classic Teams.

**Comment by leoacnesi** [comment]
We are also getting the same issue with the NEW Teams. classic teams is okay

**Comment by Carme99** [comment]
Still outstanding

**Comment by djaw123** [comment]
Hello all, I wrote this in other ticket:

I found solutions which work in my company, I updated version from 5.2 to 5.5, and then on windows 11, go to Setting in windows - Application - Installed Applications - Microsoft Teams (work or school) NEW

and try FIX (in screen Napraw)
and Reset (on screen Resetuj)

and it start works on 2 different author accounts and PC's

image

image

**Comment by gsv022** [comment]
Hi @SANCOR1 ,
Could you please let us know the status of the issue

**Comment by ATshirai** [comment]
Hello, 
We got the following  advisory message on our M365 admin center.

We are thinking if this is the solution of this issue.
How about it?

**[TM718209] 2024/02/22 4:34 JST
We’ve released an improved security for Company Communicator app template authoring experience


If action isn’t taken, Microsoft Teams users may encounter errors when authoring Company Communicator app templates.

Due to a recent security change in the Teams client, users in your organization might see an error 
while accessing the authoring experience in the Company Communicator app in Teams, with the error message
“Sorry, an error occurred while trying to access the service”. 
Users will observe this issue on the Classic Teams web client, and also on the new Teams desktop and web Clients.

To correct this issue, the app developer or admin will need to perform the below changes on the Azure portal.

Step 1: In the Azure portal, locate and select Company Communicator app Resource group by using the search bar, or
Navigate to Resource groups from the Azure portal menu.

Step 2: Select the Azure Front Door from the list of resources.

Step 3: Under Settings, locate the Front Door designer section. Select “routingRule2” that was created during the 
Company Communicator app deployment.

Step 4: Disable  the rule and save the changes.

Step 5: Restart your app service.

Step 6: Users may also need to clear the cache on the Teams desktop client(Classice Teams or new Teams).

Note: The Official Company Communicator App Template GitHub code and deployment instructions 
will be updated accordingly in the upcoming weeks.**

**Comment by leoacnesi** [comment]
> Hello, We got the following advisory message on our M365 admin center, because we have used the Company Communicator. We are thinking if this is the solution of this issue. How about it?
> 
> **[TM718209] 2024/02/22 4:34 JST We’ve released an improved security for Company Communicator app template authoring experience
> 
> If action isn’t taken, Microsoft Teams users may encounter errors when authoring Company Communicator app templates.
> 
> Due to a recent security change in the Teams client, users in your organization might see an error while accessing the authoring experience in the Company Communicator app in Teams, with the error message “Sorry, an error occurred while trying to access the service”. Users will observe this issue on the Classic Teams web client, and also on the new Teams desktop and web Clients.
> 
> To correct this issue, the app developer or admin will need to perform the below changes on the Azure portal.
> 
> Step 1: In the Azure portal, locate and select Company Communicator app Resource group by using the search bar, or Navigate to Resource groups from the Azure portal menu.
> 
> Step 2: Select the Azure Front Door from the list of resources.
> 
> Step 3: Under Settings, locate the Front Door designer section. Select “routingRule2” that was created during the Company Communicator app deployment.
> 
> Step 4: Disable the rule and save the changes.
> 
> Step 5: Restart your app service.
> 
> Step 6: Users may also need to clear the cache on the Teams desktop client(Classice Teams or new Teams).
> 
> Note: The Official Company Communicator App Template GitHub code and deployment instructions will be updated accordingly in the upcoming weeks.**

I confirm that these steps work! thank you!!

**Comment by ATshirai** [comment]
Hi, @gsv022 

Do you think  what  Microsoft Advisory tells and it is the workaround of this issue on all previous versions of Company Communicator ?
We are on version 4.1.0. Should I try them?

Thanks.

**Comment by Carme99** [comment]
@ATshirai Legend, worked for me on V5.5. Thank you so much!

**Comment by leoacnesi** [comment]
@ATshirai you should try it. We are on version 4 and did not need to upgrade. I followed what you posted and it worked.

**Comment by ATshirai** [comment]
@leoacnesi 
Thank you so much for your advice.
We think your 4.1 is working fine means ours will be working fine.
I'll try it as you.

**Comment by David-Liong** [comment]
Hi @gsv022 

My organisation is currently using Company Communicator version 5.5.
The end users have switched across using the new version of Teams in desktop and on web browser and was able to send message successfully and not having the issue error message when communicator loads up.

I also received a notification from Microsoft at the Admin portal service health  https://admin.microsoft.com/AdminPortal/home?#/servicehealth/:/alerts/TM718209

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/31954906-acaf-4017-a3a9-5788efb0e305)

So does do I still need to follow Microsoft instruction or follow your instruction in this ticket to sync if we are not experiencing the error message "Sorry an error has occurred while trying access this service" in v5.5?

Please advise.
