### ISSUE TITLE
Usure how to upgrade from 5.3

### ISSUE THREAD

**Issue by Ukiman1014** [OfficeDev/microsoft-teams-apps-company-communicator#1338]
Hello!  We deployed 5.3 back in January of 2023 and the project was shelved until just now, so I suddenly need to upgrade to the newest version.  Am I to just go through the regular PowerShell deployment, setting the "isupgrade" parameter to true?  Can or should I use the "sync" button for the app in Azure?  I believe that when the PowerShell script is finished it will produce two zip files, one for authors and one for users, which I'll then deploy to Teams to replace the current apps.  Is this correct?  I'm sorry to ask, but I am unable to find clear upgrade instructions, forum posts or YouTube videos so I'm sure of what I need to do.

**Comment by gsv022** [comment]
Hi @Ukiman1014 ,
Thanks for raising the query. Please proceed with the steps provided in [v5 migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide).  No need to go with PowerShell deployment.

Keep us posted.

**Comment by Ukiman1014** [comment]
I've successfully upgraded the app, following the steps in the v5 migration guide.  After all app and functions were successfully synced and restarted, I signed out and back into teams and the app still shows as v5.3.  Is this expected?

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/22643106/9f12e2ac-8124-4f11-8cc2-de91042bb3b5)

Also, is this where I can suggest updates to the migration guide?  I have some suggestions that could really help folks like me that have little to no experience upgrade apps like this.

**Comment by Ukiman1014** [comment]
I should mention that I'm on the New Teams.

**Comment by gsv022** [comment]
Hi @Ukiman1014 ,
The reason that the version in the about section still shows v5.3 is because the latest manifest files are not uploaded. Performing the steps as mentioned in the v5-migration guide are sufficient to run the application with latest features. If you still want the version to be changed to latest version. Then follow the below steps

- Download the latest [code](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator) from here. 
- Fill the manifest files with same app id's and app domain used in v5.3.
- Zip the manifest again and keep them ready.
- Now, go to teams admin center-->Delete the existing zipped manifest files
- Then upload the latest zipped manifest files on teams admin center.
- Wait for sometime to reflect on teams.
- Then add them to the required team. 
In this way, you will be able to see the latest version in the about section.

**Comment by Ukiman1014** [comment]
Thank you for your help!  Luckily I had the 5.3 authors and users Zip files, so I just extracted and edited their manifest files, changing the version to 5.5.  I ran into a snag when trying to upload them to Teams, because zipping them puts them in folder in the zip file.  Once I moved them out of the folder, so the three files were all that was inside the zip, it uploaded fine.

Will do some testing tomorrow.  Thanks again.

**Comment by gsv022** [comment]
@Ukiman1014 , Please let us know if you have any queries otherwise we can make it to closure.

**Comment by Ukiman1014** [comment]
I believe that I am all set for the upgrade itself.  I am still having an issue pulling up groups, but that is under issue #1348.

**Comment by tiwariShiv7** [comment]
Thanks for the info @Ukiman1014 .We are closing this issue here and we would continue to follow the groups related issue on #1348 .
