### ISSUE TITLE
Company Communicator App error message: Sorry, an error occurred while trying to access this service.

### ISSUE THREAD

**Issue by erwinnp9** [OfficeDev/microsoft-teams-apps-company-communicator#1339]
Requesting for assistance, as we are having with our Company Communicator App.

The Company Communicator App was deployed/installed successfully and the tests (message to all active users in the tenant, message sent to the channel, etc.) made after, were all OK. 

After some days, we found out that it is no longer working and we are having the message “Sorry, an error occurred while trying to access this service.” whenever we access the Company Communicator that we have added to the MS Teams.

![Company Communicator App error message](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/159126493/e341ead7-f5e7-4655-890e-a771aae3b9ed)

 Log query from the Application Insights, since we are not seeing other error logs.
 
![Screenshot of the Application Insights log query](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/159126493/51731218-ac15-41cc-99c3-bbe59d6858cc)

Thanks in advance.

**Comment by gsv022** [comment]
Hi @erwinnp9 ,
Thank you for the patience. There was a app service sync failure issue previously and is now resolved, and the changes have been pushed to Company Communicator [official GitHub repository](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414961979%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JVcWd4Z3mUGCDkrlKJekbpry%2FUCEAQQ0iqfdfMqJgDs%3D&reserved=0). 

If current deployed version of the Company Communicator application is pointing to v5.5 (latest version), please follow the below procedure to resolve the issue -

- Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center --> Click on **SYNC**

- Once the status shows successful within logs section of Deployment Center.

<img width="611" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6b02124a-cd7b-4c37-872e-7b7136d277ec">


**Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/1fe453e0-2312-42ba-a28c-796feeb1e525)

- please go to the Overview Section and restart the app service.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d208800b-e1ca-4748-b065-8172ec18e49f)

- Try accessing the CC application on Teams web client to avoid any cache related issue.

If current deployed version of the Company Communicator application is pointing to **v5.4.1 or previous versions**, please upgrade your app to latest version by following the [migration guide](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fwiki%2Fv5-migration-guide&data=05%7C01%7Cv-jaygupta%40microsoft.com%7Cdc087db078d445c02c9f08dbec1daade%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638363384414973282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vKt9QZgQYo%2FPt5r08uTTsx2bwdmbS2eBaJETCel%2B9vs%3D&reserved=0) as the fix is pushed to the **main** branch in Company Communicator's official GitHub repo.
If it’s a fresh deployment then proceed with the remaining steps as per the [deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide).
Please let us know if you are still facing the issue.

**Comment by erwinnp9** [comment]
Hello @gsv022 

Many thanks for the feedback and good to know that the **app service sync failure issue** is now resolved.
The provided procedure may have resolved the issue on our side, and we can continue to do further tests.

Many thanks.

**Comment by gsv022** [comment]
Hi @erwinnp9 ,
If you face further issues, please feel free to log the issue we will be happy to assist you.

**Comment by ashanamila** [comment]
Dear Team,

I am experiencing the same issue, but the solution provided here is not effective for my deployment. Could you assist me in resolving the issue?
