### ISSUE TITLE
Company Communicator - Author not able to open application.

### ISSUE THREAD

**Issue by e-mujica** [OfficeDev/microsoft-teams-apps-company-communicator#1342]
This is the third time I'm trying to get some help with this issue, our user has all the permissions as author but he's still unable to open the application.  User has his UPN present in the "authorizedCreatorUPN" list.
![CompanyCommunicatorIssue](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/127960941/35665c0c-3429-48b3-b9b4-6079170f56fd)

Any assistance is appreciated.

**Comment by gsv022** [comment]
Hi @e-mujica ,
Thanks for raising the query. Could you please confirm whether this is happening only with this user or with every other user also

**Comment by e-mujica** [comment]
This is the only user with this issue, would you be available for a call sometime tomorrow to look at this?

**Comment by gsv022** [comment]
Hi @e-mujica ,
Please share your mail id and we can continue the conversation internally.

**Comment by e-mujica** [comment]
Hi @gsv022 ,

The user has a E5 license.
Btw I got your email, although I'm not too familiar with this platform, I believe my mail id is 127960941e-mujica@users.noreply.github.com.  I think a call would be more beneficial and could expedite the resolution of this issue for us.  Perhaps we can set this up also?  Thanks,

**Comment by gsv022** [comment]
Hi @e-mujica ,
Please share a valid email so that we can discuss the issue internally.

**Comment by e-mujica** [comment]
Hi @gsv022 ,

Email is edwin,mujica@oakville.ca.  Thanks

**Comment by leoacnesi** [comment]
Disable RoutingRule2 in the Front Door Designer in Azure resource

Someone posted this and it helped me resolve the issue. I didn't even have to upgrade to the latest version 

**[TM718209] 2024/02/22 4:34 JST
We’ve released an improved security for Company Communicator app template authoring experience
If action isn’t taken, Microsoft Teams users may encounter errors when authoring Company Communicator app templates.
Due to a recent security change in the Teams client, users in your organization might see an error
while accessing the authoring experience in the Company Communicator app in Teams, with the error message
“Sorry, an error occurred while trying to access the service”.
Users will observe this issue on the Classic Teams web client, and also on the new Teams desktop and web Clients.
To correct this issue, the app developer or admin will need to perform the below changes on the Azure portal.
Step 1: In the Azure portal, locate and select Company Communicator app Resource group by using the search bar, or
Navigate to Resource groups from the Azure portal menu.
Step 2: Select the Azure Front Door from the list of resources.
Step 3: Under Settings, locate the Front Door designer section. Select “routingRule2” that was created during the
Company Communicator app deployment.
Step 4: Disable the rule and save the changes.
Step 5: Restart your app service.
Step 6: Users may also need to clear the cache on the Teams desktop client(Classic Teams or new Teams).
Note: The Official Company Communicator App Template GitHub code and deployment instructions
will be updated accordingly in the upcoming weeks.**

**Comment by gsv022** [comment]
Hi @e-mujica ,
We have sent a mail. Please check and respond accordingly.

**Comment by Ukiman1014** [comment]
Hello!  I am having the same issue.  My account is able to author messages but the other user who is set as an author is not.  As far as I can tell, his account has the same permissions as mine.  His UPN is also in the authors list and has a valid Teams license.  He can open the tab and see previous messages.  When he clicks to draft a new message or do anything with a prior message, he gets this error:

![Rob CC Error](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/22643106/86f48322-92e7-4908-9da1-e0ff1563693c)

I just met with Sai Venkat Gattu on Monday for a separate issue.  Please let me know if you have time to meet this week for this issue.  I previously met at 8:30 AM EST, if that works for you.  My email is swright@customersbank.com.  Thanks.

**Comment by Ukiman1014** [comment]
I should mention that we are both members of the team to which the Authors app is deployed.  I added the tab in a private channel that only he and I are members of.  I am the owner of the channel and he is a member.

**Comment by gsv022** [comment]
Hi @e-mujica ,
During the call, we asked that specific user to access the application. Still the user is getting “Sorry an error occurred while trying to access the service”.  Since the existing version is v5.3, we suggested to migrate to the latest version. We made a walkthrough on how to perform migration to latest version. User asked for our presence and guidance during upgradation. 

We will assist you if you face any issue during upgradation.

**Comment by Ukiman1014** [comment]
@gsv022 (Sai).  We are already at 5.5.1 and are still having the issue.  I have three users in the "AuthorizedCreatorUpns" environment variable (separated by semicolons), yet only one (my account) can access the Authors app without error.  I checked and everyone has app permissions to both Authors and Users.  I am not sure what is different between my account and theirs.

**Comment by gsv022** [comment]
Hi @e-mujica ,
Please let us know if you are still facing issues

**Comment by Ukiman1014** [comment]
@gsv022, I am still having the issue, though it seems that the person who opened this is the only one being addressed.  Am I to open my own case?

**Comment by gsv022** [comment]
We have replied over the mail

**Comment by gsv022** [comment]
Hi @e-mujica ,
Thanks for joining the call. The issue w.r.t 4th sending option got resolved upon updating the secrets. Now the application is up and running.

Please let us know if you have any queries otherwise, we can make it closure.
