### ISSUE TITLE
I can't see all the teams Group in my tenant

### ISSUE THREAD

**Issue by TomSawyer03** [OfficeDev/microsoft-teams-apps-company-communicator#1349]
I can only see those existing 7 Teams that is saved in Teams Data. Please help

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/85331597/6fc7a27f-8142-4bf7-8078-067b4389cb0d)

**Comment by gsv022** [comment]
Hi @TomSawyer03 ,
Thanks for sharing the query. Team Data table exclusively comprises entries for teams to which the user app has been added. In your case, user app has been added to 7 teams.

**Comment by TomSawyer03** [comment]
Why it doesn't populate all the teams that is in our Tenant?

**Comment by TomSawyer03** [comment]
and I am receiving this error too
![Uploading image.png…]()

**Comment by gsv022** [comment]
Hi @TomSawyer03 ,
Please re-share the screenshot.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/4cd3517c-314e-4372-843a-e09a1470c7d2)

**Comment by TomSawyer03** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/85331597/c2058692-db31-43f0-b952-5159324f28fc)

**Comment by tiwariShiv7** [comment]
Hi @TomSawyer03, 
Q. Why it doesn't populate all the teams that is in our Tenant?
A. That is currently how CC works. It adds the entry of teams to which the user app has been added. 

Q.  I am receiving this error too. 
A. 1. Can you please let us know what is the issue you are facing with the Company Communicator 
    2. For the error can you please help us with the number of resources the Resource group is having. To find this 
           - Go to the Resource group with which Company Communicator has been deployed. 
           - Under the overview section please check the number of resources available.

**Comment by TomSawyer03** [comment]
I got 11 resources.

**Comment by gsv022** [comment]
Hi @TomSawyer03 ,
_can we enforce the user app installation on the Teams channel instead of asking the owner or end users to do that?_
Normally we have the feature called proactive installation which installs the user app automatically. This is present in newer and older versions as well. For the first and second sending option, to have the team name appeared under the dropdown user app needs to be added to the specific/targeted team then it sends the message  as post or to sends message all the members of the team individually. But for 4th sending option, if user app is available at the tenant level then to which ever team/DL that we try to target proactive installation will check the user app present at the tenant level or not and send the messages accordingly to the DL/team.

-  if the Author is a member of the Teams channel then the author could send cards to that channel. In the latest version that is not available
Could you please share detailed findings by differentiating both scenarios with author presence and without author presence.

**Comment by TomSawyer03** [comment]
I'm checking...

**Comment by gsv022** [comment]
Yes, please keep us posted

**Comment by TomSawyer03** [comment]
> Hi @TomSawyer03 , _can we enforce the user app installation on the Teams channel instead of asking the owner or end users to do that?_ Normally we have the feature called proactive installation which installs the user app automatically. This is present in newer and older versions as well. For the first and second sending option, to have the team name appeared under the dropdown user app needs to be added to the specific/targeted team then it sends the message as post or to sends message all the members of the team individually. But for 4th sending option, if user app is available at the tenant level then to which ever team/DL that we try to target proactive installation will check the user app present at the tenant level or not and send the messages accordingly to the DL/team.
> 
> * _if the Author is a member of the Teams channel then the author could send cards to that channel. In the latest version that is not available_
>   Could you please share detailed findings by differentiating both scenarios with author presence and without author presence.

How can I do the proactive installation?

**Comment by gsv022** [comment]
Hi @TomSawyer03 ,
During the ARM template filling, there will be a field called ProActiveInstallation where it can be set as true or false. By default, it will be set to true. Here is the reference.
<img width="394" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/0d116d6a-774c-45fc-b408-2455e67c6e5e">


Please let us know if you are having any further queries.

**Comment by gsv022** [comment]
Hi @TomSawyer03,
No, Proactive installation makes the automatic installation of user app for the users in the team but user app should be available at the tenant level for the fourth sending option/Third Sending option.
