### ISSUE TITLE
Multiple bad request

### ISSUE THREAD

**Issue by GregoryBrunn-ms** [OfficeDev/microsoft-teams-apps-company-communicator#1366]
Microsoft.BotService/botServices/channels

request are throwing bad request

same with 

Microsoft.Web/sites/sourcecontrols

**Comment by gsv022** [comment]
Hi @GregoryBrunn-ms ,
Thanks for raising the query. This issue has been followed up internally

**Comment by gsv022** [comment]
Hi @GregoryBrunn-ms ,
Thanks for joining the call. Here is the call summary - 

- During the call it is observed that deployment is failed, and error indicates that "Creation of storage file share failed with: 'The remote server returned an error: (403) Forbidden.'. Please check if the storage account is accessible."

- We observed that in the storage account networking section- Enabled from selected virtual networks and IP addresses is the option selected under public network access. Due to this the deployment is failing. We asked the user to change it to Enable from all networks. The change is not getting reflected due to the overriding of policy where it is not allowing to change to other options. We have explained implications involved if not changing to required option and level of security measures taken care from application side.

- There are other failures in the deployment where function apps and app service got failed. After visiting the resources individually, there are success(Active) in the deployment center.

- There are 26 resources residing under same resource group. We recommended to keep the resources relevant to CC under one rg.

-  We mentioned that we will grab more information from our end on storage account issue. Meanwhile user mentioned that he will try to get it changed to required option in the storage account networking section.
