### ISSUE TITLE
Company Communicator v5.5.2 Critical and high security alerts release update 

### ISSUE THREAD

**Issue by SachinWandale111** [OfficeDev/microsoft-teams-apps-company-communicator#1403]
Hello team
About the Company Communicator release upgrades, they have mentioned, "Updated libraries to address critical and high security alerts.". We are now using version 5.3.0 of company communicator in our Production tenant; therefore, we would like to know if there will be any effects on any configurations or other aspects of the current version. Please refer below  GitHub link for Company Communicator v5.5.2 release upgrades. Also find the above screenshot attached.
GitHub link ----> https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/releases
Screenshot ----> <img width="616" alt="v5 5 2 release" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/160738265/76d389ed-374a-44f5-b12a-319ab511ed12">

**Comment by gsv022** [comment]
Hi @SachinWandale111 ,
Thanks for raising the query. It is highly recommended to upgrade the application to latest version due to the following reasons.

- Classic Application insights got retired by Feb 29, 2024. Please refer to this [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#migrating-classic-application-insights-to-workspace-based-application-insights) and do the necessary.
- Since the app is already on v5.3 then .NET upgrade and function run time version upgrade might have been completed as per the migration guide. Now, please refer the [Step-2-Validate and update the config settings and sync to the lastest code](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#2-validate-and-update-the-config-settings-and-sync-to-the-lastest-code-) and add which ever parameter is missing the app service configuration. Once the parameters are added then don't forget to SYNC app service within deployment center.
- There was problem encountered in v5.5 on Authorization of CC. Please refer to this [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Support-policy#for-owners-of-personalized-company-communicator-editions)
- Authorization issue has been addressed in the latest version. For more details, please refer [here](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix)

**Comment by SachinWandale111** [comment]
Thanks for sharing the information. We will get back to you if any more information required in above case.

**Comment by gsv022** [comment]
Hi @SachinWandale111 ,
Please keep us posted

**Comment by SachinWandale111** [comment]
Sure.
