### ISSUE TITLE
Missing ServiceUrl in AppConfig and User Table

### ISSUE THREAD

**Issue by gittyNico** [OfficeDev/microsoft-teams-apps-company-communicator#1418]
Hello,

I am currently implementing the Company Communicator (fresh installation starting v5.5.2) using custom domain.

My issue is, that the ServiceIUrl is not set in the AppConfig table nor the UserData or TeamData table. Setting the value manually magically makes the whole deployment working. Same with testing the "Start-ChatWithSpecifiedUser.ps1" script.

I would like to know where the table entry is coming from and what I can do to make it populated automatically. Can I check any permissions, environment variables, etc.?

Thank you in advance for you help!

**Comment by gsv022** [comment]
Hi @gittyNico ,
Thanks for raising the query. 

- Normally, using default domain there is no such missing of ServiceUrl in the AppConfig table.  Since you are mentioning deployment done with custom domain we are not sure here.  The support scope is very limited to standard version using default domain. We recommend the steps that need to be followed for [Custom Domain](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Custom-domain-option) implementation. 

To observe the difference, we recommend one round of deployment using default domain.

- Please share the script- Start-ChatWithSpecifiedUser.ps1 that you tried.
