### ISSUE TITLE
Query reg. to Icon changed for Company communicator app in teams

### ISSUE THREAD

**Issue by SachinWandale111** [OfficeDev/microsoft-teams-apps-company-communicator#1430]
Hi team,

In our Tenant customer recently reported that, the icon of our Company communicator application in Teams app (New teams) has changed automatically.
And also they have noticed that the same icon is being used in other application (ServiceNow app), as shown in the attached screenshot.
The icon for ServiceNow back again automatically and our company communicator icon back after teams cache cleared.
Now again customer reported the same issue the same icon is being used both applications.
Could you kindly check and let us know if the other customer also reported similar issue so far and the provide us next action plan?
We already tried clear cache for teams application as well- It worked after clear cache.
Web application - No issue reported.

<img width="205" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/160738265/876a389f-e2dc-43e7-b350-1c10167e1a9a">

**Comment by v-jaygupta** [comment]
Hello @SachinWandale111 ,

Thanks for reaching out to us!
As per the details provided this looks more of a tenant related issue as the CC app has its own logo icon uploaded at teams level and it reflects in the web app client and after clearing the local cache of the Teams desktop client, but due to some other issue its reflecting the icon of a different app in the desktop client.
Requesting you to please reach out to Teams support for further assistance on this issue.

**Comment by SachinWandale111** [comment]
Thanks for update.

**Comment by gsv022** [comment]
Closing the issue as we provided response to the query asked. Please feel free to reach out to us on queries related to CC, we would be more than happy to assist you.
