### ISSUE TITLE
Error when trying to compose a new message - Oops! An unexpected error seems to have occurred.

### ISSUE THREAD

**Issue by thowardtw** [OfficeDev/microsoft-teams-apps-company-communicator#1432]
Hi,

I've just followed the deployment guide through:
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide

I've added the Company Communicator to a Teams channel as a tab. When I go to try and do a new message, I get an error like this:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168735484/52b66376-702a-4b2d-84c4-eee08ba759bf)

What's the best way to troubleshoot this error?

Thanks

**Comment by v-jaygupta** [comment]
Hello @thowardtw ,

Thanks for reaching out to us!

Could you please share the error details and supporting screenshot of error from CC app or application insights from the deployed resource group to investigate on this issue.

Also, share deployment status screenshots of all the Function apps and App service from the deployment center by following the below steps. Here is the reference for App service status. Please do the same for 3 function apps(Data Function, Send Function, Prep Function).

Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select app service **(do the same for 3 function apps)** from list of resources-->Go to Deployment Center-->Click on Settings **(share a screenshot)** --> Click on Logs **(share a screenshot)**

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/115773960/f735973f-ba9b-43e7-b2cb-c7a3ac5eb2d4)


In addition to this, can you please cross check the values of client secret for User, Author & Graph app from azure key vault and make sure the values are same as generated at the time of App registrations or there might be chance that the secrets might have expired.

This will help us to find the root cause and fix it quickly.

**Comment by thowardtw** [comment]
Thanks for your feedback. I managed to fix the error by redeploying from scratch.

**Comment by gsv022** [comment]
Please feel free to log the ticket f you face any issue related to CC

**Comment by gsilvaads** [comment]
Hi @v-jaygupta, greetings!

I have a similar problem. When adding Teams Communicator to the Channel tab, it shows the home screen, but when clicking on Send New Message, it shows an error without reference. Would you help me?

Data Function:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/aaf88a96-1419-4c60-8afd-f1176cb84964)

Function:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/0883543d-56ba-4bf6-b560-faf6d307ec52)

Prep Function:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/1f4db8d8-d892-47e5-a20d-35e0eb5260ea)
