### ISSUE TITLE
What is the MIT license? Is there any piece of code to do with sending our data /Information for MIT?

### ISSUE THREAD

**Issue by Rajatextoutokumpu** [OfficeDev/microsoft-teams-apps-company-communicator#1433]
Hi, our client wants to know the security aspects of MIT License and how it will affect their environment? Could it be that the apps have a piece of code that would actually send information to MIT on the usage? It would explain the need to have multitenant setup here.

Please explain it, in the documentation it's not mentioned clearly about MIT License for this and who is responsible in case of any data breach.

**Comment by gsv022** [comment]
Hi @Rajatextoutokumpu ,
Thanks for raising the query. Please give us sometime, we will get back to you with proper response.

**Comment by Rajatextoutokumpu** [comment]
Hi @gsv022 , any update on this?

**Comment by Rajatextoutokumpu** [comment]
Hi @gsv022 , still no response on this issue. Please clarify asap. Why its taking so much time ?

**Comment by gsv022** [comment]
@Rajatextoutokumpu , there is no such piece of code that sends data to MIT. The purpose of having multi-tenant at the time of implementation due to the below reason.
- As per the deployment guide, author and user app should be kept as Multiple Org where as Graph app should be kept as My Organization.
- Bot Framework SDK's works usually on the multi-tenant app type only. Otherwise the functionality breaks for sure. Here is the [reference](https://learn.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0&tabs=userassigned#manual-app-registration).
<img width="462" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/18b6f0c1-9b78-4968-ae84-bbd7f9f20ce0">

--------------------------------------
- We have taken care of security risks at various levels like at the code level and at the resource level by having proper authentication and authorization. 
- There is a parameter called-"AuthorizedSenderUPN" within App service, only who have their UPN's within that parameter will have access to the application. 
- We have key vault as one of the resources to mask the app secrets and storage account connections etc.,
- There is a parameter called-"AuthorizedDeleteUPN" within App service, only who have their UPN's within this parameter will have access to the deletion of sent message records.
