### ISSUE TITLE
Issue with MS Teams new version

### ISSUE THREAD

**Issue by viralkagathara** [OfficeDev/microsoft-teams-apps-company-communicator#1471]
Dear MS Team,

We are using the Microsoft Teams Company Communicator version "CC v5.5 release changes (#1147)" in our production environment. While the end-user application is functioning correctly, the Author console is not working with the new version of MS Teams. It continues to work in the classic version of MS Teams, which will be discontinued from July 1st.

Can you please guide us on how to fix this issue?

Additionally, if this issue is fixed in the latest update v5.5.2, can you provide details on the impact on our product if we upgrade? Your prompt response would be greatly appreciated.

Best regards,
Viral

**Comment by gsv022** [comment]
Hi @viralkagathara ,
Thanks for raising the query. Since the version is on v5.5, we recommend you to upgrade it to the latest version where we have addressed authorization issue coming up due to the introduction of new teams. Follow the below steps.

- Perform migration of classic application insights by following this [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#migrating-classic-application-insights-to-workspace-based-application-insights)
- Perform the removal of routing rule by following this [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix)
- Then perform SYNC for all the resources-App Service, 3-function apps

There are no implications upon upgrading to the latest version. No data loss, No impact on the functionality.

**Comment by viralkagathara** [comment]
Hi @gsv022 , Thanks for your prompt response.
