### ISSUE TITLE
Can't export status of messages.

### ISSUE THREAD

**Issue by Camboya466** [OfficeDev/microsoft-teams-apps-company-communicator#1485]
Hi all,

when I try to export the message status appears this message:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122912317/42d242d0-4b6e-4020-8797-98bf39460458)

I reviewed all enviroments variables and all are set correctly.

Best regards,

**Comment by v-jaygupta** [comment]
Hello @Camboya466 ,

Thanks for reaching out to us!
Please allow us some time, will check and get back to you with proper response.

**Comment by v-jaygupta** [comment]
@Camboya466 ,

Could you please share the error details and supporting screenshot of error from CC app or application insights from the deployed resource group to investigate on this issue also, confirm on the version of the application deployed in your tenant.

In addition to this, can you please cross check the values of client secret for User, Author & Graph app from azure key vault and make sure the values are same as generated at the time of App registrations or there might be chance that the secrets might have expired.

This will help us to find the root cause and fix it quickly.

**Comment by Camboya466** [comment]
Hi @v-jaygupta 

Thanks for yor answer.

I was checked the App Insights:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122912317/b1bc816b-7d0e-4b1f-b792-f304367a321c)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122912317/47905b39-75af-4a55-8185-8c378442ffd2)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122912317/82b88404-cb97-40dd-bb59-15f585985a10)

I checked the enviroment variables and all values are correct.

the current version is 5.5.2

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122912317/f31ece83-84ae-4e23-bb6b-4c8432bae1ad)

Thank for you help.

!!

**Comment by Camboya466** [comment]
@v-jaygupta 

Do you have any comment about this topic?.

Thanks

**Comment by tiwariShiv7** [comment]
Hi @Camboya466, Can you please verify if the [Auth Issue Fix ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix) changes are correct in your repo ?

**Comment by Camboya466** [comment]
Hi @tiwariShiv7 

I have applied the configuration but the error persists.

Best regards.
