### ISSUE TITLE
Deployed with App registrations, getting 401 responses (not authorized)

### ISSUE THREAD

**Issue by AyTonyM** [OfficeDev/microsoft-teams-apps-company-communicator#1593]
We deployed the application following the deployment guide. It was successfully deployed, however, we're seeing:
![image](https://github.com/user-attachments/assets/94fd4087-5085-485f-a864-7a464287ac5c)"

GET /api/sentnotifications 
Response code | 401

I have:
- verified the secrets in the key vault are correct
- re-synced the function apps and app service
- added the six graph api permissions and granted admin consent
- configured the scope for the graph api as well (api://redacted.azurefd.net/access_as_user)

![image](https://github.com/user-attachments/assets/bf73da50-82de-4464-8186-e5dcd5de6495)
![image](https://github.com/user-attachments/assets/9724f675-c919-4093-97cf-27c1786f1b20)
![image](https://github.com/user-attachments/assets/c8f37ea5-fb48-49ca-8d84-9ea4d05a7b4d)

App Service: 
![image](https://github.com/user-attachments/assets/5734b81e-7316-4227-9792-4ade4081b372)

**Comment by peddivyshnavi** [comment]
Hi @AyTonyM 
Thanks for reaching out to us
sorry for delay in response we will get back to you ASAP

**Comment by peddivyshnavi** [comment]
Hi @AyTonyM 
Upon review, we have see that the supported account type for the graph app registration is currently set to multi-tenant. Could you please update it to single-tenant
for reference :
<img width="734" alt="image" src="https://github.com/user-attachments/assets/e46b2d05-3f79-4c77-907b-ee73f84f25e5">
[deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#1-register-azure-ad-application)

**Comment by AyTonyM** [comment]
Here's another screenshot of App Insights:
![image](https://github.com/user-attachments/assets/764b8085-5b0f-482e-8ba7-efef9d86cd51)

**Comment by peddivyshnavi** [comment]
Hi @AyTonyM
Thanks for reaching out to us
we will get back to you ASAP

**Comment by peddivyshnavi** [comment]
Hi @AyTonyM 
Could you please check whether secrets got updated correctly in all app functions and app service 
as well as could you please validate app domain value in manifest file

**Comment by AyTonyM** [comment]
The manifest files for both the users and author files match the output from from the deployment:
![image](https://github.com/user-attachments/assets/045e1bcc-d450-46a4-9b90-b2e5c164f6b8)
![image](https://github.com/user-attachments/assets/4c7b5a47-7116-4668-94d4-fe25e633d0ed)


Additionally, all of the connection strings point to valid key vault secrets, and I confirmed that those secrets correspond to the correct app registrations. 

Does the user or author app registration need any api permissions like the graph app registration?

**Comment by peddivyshnavi** [comment]
Hi @AyTonyM 
have you updated manifest section which is under manage in graph app registration.

**Comment by AyTonyM** [comment]
Here's a screenshot of the section from the manifest file that was updated:

![image](https://github.com/user-attachments/assets/fdb8b790-f912-4f49-aba8-6b65bea20e97)

**Comment by peddivyshnavi** [comment]
Hi @AyTonyM 
we will check and will get back to you

**Comment by peddivyshnavi** [comment]
Hi @AyTonyM 

- Could you please check whether Supported account types for author app registration and user app registration is assigned as multitenant

could you please validate whether secrets got updated correctly
**basically, we need to copy value which in Value instead of secret id for app registrations secrets**
for validating 

- please navigate to app registrations 
- on left hand side you will have option manage under that click on certificates and secrets 

- we will able to see value

<img width="908" alt="image" src="https://github.com/user-attachments/assets/9e9b2ab1-87b3-4bc8-8650-7e0f93e587b3">

- Now navigate to key vaults in resource group where CC is deployed
- On left hand side you will see objects under that click on secrets

![image](https://github.com/user-attachments/assets/d6a858cb-1d6a-4e2b-9882-4a4cff6ae7ff)

- If the secrets are not visible, Go to Access Policy--> Click on Create
- ![image](https://github.com/user-attachments/assets/dccf4ced-57b5-4fde-b0b8-2bf96d0965b4)

- Select Key, secret and certificate management
- ![image](https://github.com/user-attachments/assets/a170d4d1-de50-408e-b6e0-a22714a7c642)

- Give the Id through which one can view the secrets
- ![image](https://github.com/user-attachments/assets/37b6f749-66c9-443d-9201-a9b7f2f919f4)

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. Open author/user/graph app password

![image](https://github.com/user-attachments/assets/a0ca49dd-ebd4-471f-8600-0aee317822d8)

- click on current

![image](https://github.com/user-attachments/assets/63fadd76-178a-4054-8b1d-02dcab796b9c)

- you will be able to see secret value column copy that 
- paste in notepad or some where please check whether they are same as values not secret id in app registartion
- please validate this for all app registration

**Comment by AyTonyM** [comment]
Hello @peddivyshnavi ,

I have verified that the key vault secrets match the values (not secret ids) for all of the app registrations.
ex) 
![image](https://github.com/user-attachments/assets/fa6fcf5b-37d7-4a86-a94a-f2d5a9f11ca7)
![image](https://github.com/user-attachments/assets/013a61fa-9f85-45a0-b2af-f029aecdb43f)
And I have done this with the user and author app registrations as well. 

The Users and Author app registrations were set to multi-tenant. Should those also be single?

Thank you.

**Comment by AyTonyM** [comment]
We were able to send a successful message. It turns out, that the app had previously been installed a few versions ago, and there were multiple Author apps in Teams. We removed all of them and uploaded the corrected version and it worked during testing.
