### ISSUE TITLE
Oops! an Unexpected Error seems to have occurred. Why not try refreshing your page? Or you can Contact your administrator if the problem persist. 

### ISSUE THREAD

**Issue by fatsbear** [OfficeDev/microsoft-teams-apps-company-communicator#1604]
![image](https://github.com/user-attachments/assets/dd58e3f1-bab1-4f2d-8ae4-68e9f0bc04e7)

what is causing this whenever i try to write a new message. Going through a custom domain if that makes a difference.

**Comment by tiwariShiv7** [comment]
Hi @fatsbear, 
Thanks for reaching out. This generally happens either due to secrets expiry or configuration mismatch. 
You can recheck deployment steps and compare everything carefully. 

Our support scope is limited to the Official repo of Company communicator according to our [support policy ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Support-policy).

Can you confirm that by Custom domain you meant Custom repository ?

**Comment by fatsbear** [comment]
custom domain(https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Custom-domain-option) not azure front door. BUt i'll check the secrets(although this is a brand new deployment) and configuration,

**Comment by fatsbear** [comment]
yeah creating new secrets and updating the configs worked. This can be closed.
