### ISSUE TITLE
Is there any character limitation for the messages?

### ISSUE THREAD

**Issue by Axael85** [OfficeDev/microsoft-teams-apps-company-communicator#1623]
Is there any chacaracter limitation for the body message for company communicator? We are going to send a pretty large message on the company.

REgards

**Comment by v-milibiswas** [comment]
Hello @Axael85,       
Thanks for reaching out to us!
Please note that while there is no specific limitation on the length of the text from the application side, the adaptive card size should be less than 40 KB due to constraints from the adaptive card and Teams. Additionally, it is advisable to send a message first to a test group to confirm if the message is successfully delivered.

**Comment by Axael85** [comment]
Thanks for the comments @v-milibiswas , I was looking for the information but couldn't find it. We can consider this as closed .
