### ISSUE TITLE
Unable to Find Teams within the Organisation

### ISSUE THREAD

**Issue by JoeSMGraham** [OfficeDev/microsoft-teams-apps-company-communicator#168]
We are currently having an issue with the Author side of the app where we can only communicate with the Team that has the Author app embedded within it.

Correct me if I am wrong, we were under the impression you would be able to send comms cards to individual teams or members of individual teams across the organisation.

Please confirm, any advice would be appreciated.

**Comment by JoeSMGraham** [comment]
As with users, does the Company Communicator app need to be present with the different teams across the organisation?

**Comment by rashmi-dixit** [comment]
You need to install user app to different teams you want to communicate with not the author app.
By default, you can also communicate to the team where author tab is added but for recipient team you have to add user app.

![image](https://user-images.githubusercontent.com/57787129/82875284-d3efd180-9f54-11ea-9c86-9f7087903ace.png)

This is how the 3 options for sending messages will work for the author tab-:

- **Send to General channel of specific teams**: Author can select teams from the dropdown whom the messages is intended for. The message will be sent in general channel of the recipient team.

- **Send in chat to specific people**: The message will be sent in personal (1:1) chat of the selected team’s members. 

- **Send in chat to everyone:** The message will be sent in personal (1:1) chat of all the users who have installed the company communicator-users app.

**Comment by divurgentuser** [comment]
What's weird is you have to set up a new Teams channel that *never gets used*, in order to message a user directly (i.e. outside the channel).

Does it have to be this way? Perhaps use security groups or something, instead of spinning up Teams channels just to have a user list?

Why is it that in the dropdown for "Send in chat to specific people" you only see teams (aka unused dormant channels) and can't select individuals?

**Comment by rashmi-dixit** [comment]
You cannot send messages by using security groups or distribution lists in the current version.
The dropdown for "Send in chat to specific people", will only show teams where end-user app is installed. By using this option, the message will be sent to individuals of the selected team. 
Hence to send message to specific people, add those people to a team first and install end-user facing app in that team so that it appears in the dropdown for "Send in chat to specific people"

**Comment by divurgentuser** [comment]
Thanks @rashmi-dixit for confirming. This of course is less than ideal so I hope improving this situation is part of the product road map.

**Comment by UmerShoukat** [comment]
@rashmi-dixit - i have installed end-user facing app to all users via Teams Admin portal. should i be able to search users when trying to send to specific users ?
i have installed latest app version and it shows the option for sending messages to Sec/Dist groups but it says i would need permissions ? can you suggest how i get this option working ?

**Comment by juna-gupta** [comment]
@divurgentuser We have added support to send messages to Security / Distribution / M365 groups. Try the latest version.

@GHNinja Make you the admin grants the permissions. You may refer to [this section](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-app).
