### ISSUE TITLE
Stuck in Login Loop in Authors App 

### ISSUE THREAD

**Issue by apptemplatequestions** [OfficeDev/microsoft-teams-apps-company-communicator#188]
Hi,

I just deployed the company communicator to my tenant and have added it to Teams as an admin. I then added the app to a test-team for authors, but I now get stuck in a login loop whenever I want to login to the authors app in order to create messages.

Teams only shows me a couple of screens in very fast motion and I then land back on the "sign in" screen without being able to type or do anything.

Does anyone know how to fix this issue?

Thanks in advance for your help!

**Comment by sergiorru** [comment]
Hi @apptemplatequestions 

I faced this issue when i misconfigured the Expose an Api settings of the AAD App Settings.

And don't forget to check the webApplicationInfo in the teams app you must specify:

"webApplicationInfo": {
      "id": "<APP ID (an Guid)>",
      "resource": "api://<app configured>"
  }

**Comment by kahopkin** [comment]
I am having the same issue.... I configured everything in the Expose API settings as instructed, and properly updated the manifest.json file also, however, it is in a forever sign in loop.  It's worth mentioning that this only happens when during the deployment the tenant ID is different from the subscription's tenant.  My subscription doesn't allow me to switch tenants for the subscription and the "stuck in Sign in" loop holds true so far for any app template I tried to deploy with the subscription...

**Comment by dj1298** [comment]
@kahopkin Take a look at my recent post in issue #200. I discuss the use of multiple tenants.

**Comment by juna-gupta** [comment]
@apptemplatequestions @kahopkin This usually happens when the tenantId configured is different from the tenant where you're installing the teams application. Please ensure that the tenantId configured matches the tenant where you are installing the teams application (subscription tenant could be different!).
