### ISSUE TITLE
Why is TeamsAppInstallation.ReadWriteForUser.All required? 

### ISSUE THREAD

**Issue by cbitter78** [OfficeDev/microsoft-teams-apps-company-communicator#240]
# Overview

In an enterprise it is not suggested to delegate TeamsAppInstallation.ReadWriteForUser.All to a single app.   This would mean that the application could re-write (delete, change, update, etc) all apps in a tenant.

Can we reduce the permissions required?

**Comment by bungleweed** [comment]
I think its required for the proactive app installation.

**Comment by cbitter78** [comment]
Do you think it could be skipped if side loading the bot?

**Comment by ktcodebite** [comment]
This is the permission that allows for the proactive app installation feature that was part of the V3 release. Before this feature was available, only users that had the Company Communicator app installed would receive a message sent to them. Meaning you would either need to install the app for all users via the Teams admin center or ask everyone to side-load the app. With proactive installation, the app will auto-install to users that receive a message, and users will not miss a message intended for them because they don't have the app installed.
If you don't want to use the proactive installation and want to avoid giving the app the TeamsAppInstallation.ReadWriteForUser.All permission, you can disable proactive installation by:
1. At the time of deployment, there is a setting to configure proactive installation. Default is true.
2. Post deployment, in the Azure App service and Prepare Function configuration - set the ProactivelyInstallUserApp to false.
Learn more about the feature in the Solution Overview as well: https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Solution-overview#azure-function

**Comment by cbitter78** [comment]
Can we get this added to the deployment wiki?  I am happy to do that,  Not sure if I have the access.

**Comment by juna-gupta** [comment]
@cbitter78 Does [Step 6 (iv)](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#2-deploy-to-your-azure-subscription) help in identifying the right setting while deploying the application?

You may also refer to [this section](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Solution-overview#app-permissions) to learn about all the Graph permissions.

**Comment by cbitter78** [comment]
The parameter section shows you can turn the install feature off and the troubleshooting section shows the need to have permissions but nothing connects the two.   I was an able to find anything that explicitly explains what setting the proactive install would do and how that would affect the need permissions

**Comment by cbitter78** [comment]
I am happy to update the doc if there is a way I can contribute
