### ISSUE TITLE
Resource unavailable

### ISSUE THREAD

**Issue by garystewart247** [OfficeDev/microsoft-teams-apps-company-communicator#250]
Getting 'The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.' when the app calls the https://[domain].azurefd.net/configtab URL.

**Comment by juna-gupta** [comment]
Could you check if the application service is available? Go to https://<domain>.azurefd.net/. Please also verify that the URL provided in the manifest is correct.

If your app deployment failed due to some reason, go to Deployment Center and tap on Sync. (access [this](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#fix) for more details)

**Comment by RCormier-MSFT** [comment]
I get the same.  Deployment shows successful.  Browsing directly to appdomain/configtab returns the same message.  Browsing just to the app domain says the app service is up and running, says "time to take the next step and deploy your code".

**Comment by juna-gupta** [comment]
@garystewart247 Are you still getting this issue?

@RCormier-MSFT Did you try Sync option in Deployment Center?

**Comment by garystewart247** [comment]
Yes this same issue exists.  Not sure why this is occurring.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RCormier-MSFT** [comment]
@juna-gupta  - Yeah, I tried to sync in the deployment center.  I tried redeploying a few times in different environments.

**Comment by garystewart247** [comment]
I had to redeploy the app and it is now working.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
