### ISSUE TITLE
M365 groups

### ISSUE THREAD

**Issue by biancafrigerioMS** [OfficeDev/microsoft-teams-apps-company-communicator#254]
Hello,

I cannot retrieve M365 security groups from the template, it says that I have no permission to do it but I gave all the permission correctly.

![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/57915354/100352992-1c647680-2fee-11eb-871f-04739a7c8c08.png)

Can you please help me? @juna-gupta

**Comment by cankanat** [comment]
I have same problem too

**Comment by juna-gupta** [comment]
@biancafrigerioMS @cankanat Please double check that the admin has granted all the permissions mentioned in this [section](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-app).

The issue is expected when Group.Read.All delegated permission is not granted. Details [here](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Solution-overview#microsoft-graph-api).

**Comment by biancafrigerioMS** [comment]
I gave all the permissions as follows: @juna-gupta 
![image](https://user-images.githubusercontent.com/57915354/100726353-23f89680-33c5-11eb-8bde-a9357462b42f.png)

**Comment by juna-gupta** [comment]
@biancafrigerioMS "In Teams I use another tenant. is this a problem?" Yes, this will create a problem as the permissions are not granted in the tenant where you are using the application.

You could prepare a link - https://login.microsoftonline.com/common/adminconsent?client_id=%appId%. Replace the %appId% with the Application (client) ID of Microsoft Teams bot app and share with the global administrator to grant the requested permissions. 

If you have admin credentials for the tenant where you are installing the teams application, you could open the link in Incognito/Private mode and login with the admin account to grant the permissions.

**Comment by biancafrigerioMS** [comment]
Thank you now works! @juna-gupta

**Comment by juna-gupta** [comment]
@biancafrigerioMS You're welcome. Closing the issue.
