### ISSUE TITLE
Permission issue as author. 

### ISSUE THREAD

**Issue by billcruze** [OfficeDev/microsoft-teams-apps-company-communicator#255]
My UPN is already added in the configuration tab in the parameter "AuthorizedCreatorUpns" but when uploading the zip manifest file I am getting this error: 

Permissions needed
Only meeting organizers and presenters can manage tab for this meeting.

![Permission Error](https://user-images.githubusercontent.com/53074727/100365324-55402380-2fcd-11eb-915a-b7108a334c1d.PNG)

**Comment by juna-gupta** [comment]
@billcruze This issue is probably due to app permission policy configured. Please refer to this [documentation ](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams) to learn more.

The UPN configuration is to restrict who can send the messages using Company Communicator Author application.

Closing the issue. Please re-open if you have any trouble with the app template.
