### ISSUE TITLE
Size of the Image

### ISSUE THREAD

**Issue by VictorPrado1** [OfficeDev/microsoft-teams-apps-company-communicator#312]
Hi, I've been looking for the specific limitations of the Company Communicator. Our last search on the github showed 1MB limit for a Image, but some tests with Images until 2MB worked as well. 

Also I haven't found any information about characters limitations (I've been using 1.000 characters as a reference). 

Can you guys help me out with those informations?

**Comment by shridharp-ms** [comment]
@priyank29 Need guidance on this

**Comment by aosolis** [comment]
The underlying limit for images comes from the Teams platform, and the current limits are documented here: https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#inline-card-images

For text, 1,000 characters is a good conservative size. Two limits come into play here:
- Bots can send a maximum message size of 28KB (this is for the entire message).
- Azure table storage has a maximum size of 64KB per cell

If you are unsure of these limits, we recommend using the "Preview" function to send it to the authors team first. (In fact we recommend doing this always, since there can be some differences between the preview in the app, and how the card is ultimately rendered in Teams.)
