### ISSUE TITLE
Decommissioning v1

### ISSUE THREAD

**Issue by JoeSMGraham** [OfficeDev/microsoft-teams-apps-company-communicator#347]
I have created a new app registration for V4.  Please can you provide some guidance how to decom v1 app registration?  And can we deploy v4 while v1 is in place?

**Comment by hunaidhanfee20** [comment]
Hello @JoeSMGraham,
If you are doing fresh deployment you can have both the app version there's no issue in that. But if you are going to do that you will need to update manifest Ids of both user and author manifest because default will be used in v1 version. 
Both version will be having different storage so you will not able to see messages from v1.

To delete App registration : Go to App registration -> Search your registration ->
![image](https://user-images.githubusercontent.com/64194049/119860627-25e68100-bf34-11eb-88dc-a93dd798e79c.png)

Let us know if you have any doubt.
Thanks
