### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by ByroneO** [OfficeDev/microsoft-teams-apps-company-communicator#364]
the upgrade instructions are from v1.. can someone update for other versions?

**Comment by SubbaReddi** [comment]
V1 -> V2 -> V3 -> V4. Follow migration guides.
Otherwise do the fresh deployment which is with V4.

**Comment by hunaidhanfee20** [comment]
Hello @ByroneO,
Which version you are having right now?
You can follow these migrations guide: 

- [Migration Guide v1 to v2](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Migration-guide) 
- [Migration Guide v1.x to v2](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v2-migration-guide) 
- [Migration Guide v2.x to v3](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v3-migration-guide)
- [Migration Guide v3 to v4](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v4-migration-guide)

Else you can do a fresh deployment using [Azure portal deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide) and [deployment guide PowerShell](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide-powershell)

Hope this issue is solved for you.
Thanks
