### ISSUE TITLE
Can send to all but one user account - 'serviceUrl' cannot be null or empty

### ISSUE THREAD

**Issue by glblinck** [OfficeDev/microsoft-teams-apps-company-communicator#446]
Using Company Communicator, we are successful in sending to all but one account in the tenant. The sending account never receives the message, with the log saying "'serviceUrl' cannot be null or empty". Any idea how to address this? Version 4.1.2 is installed and seems to work for everything but sending to the one account.

Member | Failed | -2 : System.ArgumentException: 'serviceUrl' cannot be null or empty (Parameter 'serviceUrl')

**Comment by snailCorpse** [comment]
Make sure that when you created the app registration you selected multi tenant as the option.

Also make sure that all the url settings on the app  configuration matches the correct url created by the ARM template

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Glenn Blinckmann ***@***.***>
Sent: Monday, June 28, 2021 8:31:11 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OfficeDev/microsoft-teams-apps-company-communicator] Can send to all but one user account - 'serviceUrl' cannot be null or empty (#446)


Using Company Communicator, we are successful in sending to all but one account in the tenant. The sending account never receives the message, with the log saying "'serviceUrl' cannot be null or empty". Any idea how to address this? Version 4.1.2 is installed and seems to work for everything but sending to the one account.

Member | Failed | -2 : System.ArgumentException: 'serviceUrl' cannot be null or empty (Parameter 'serviceUrl')

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fissues%2F446&data=04%7C01%7Cstephena%40tihsa.co.za%7Cb5e467176c884fa0f76608d93a62e85b%7C8db3ceb8744648bc8bb497803c527a37%7C0%7C0%7C637605018854263559%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lPM4dCPWdlnRFtdB%2BlWAoy1s5GIeuxmXMvNoFAsnKhI%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGEUQZEUO5P4WMGG6NRRY4DTVC5W7ANCNFSM47OPW72A&data=04%7C01%7Cstephena%40tihsa.co.za%7Cb5e467176c884fa0f76608d93a62e85b%7C8db3ceb8744648bc8bb497803c527a37%7C0%7C0%7C637605018854263559%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NO%2B6GgDtUSWFBYTLuab6bCue3hOYSkcFVB33jYu6Ou4%3D&reserved=0>.


Suitable for Public Use

**Comment by glblinck** [comment]
Checked the app registration and configuration. Both were correct. I had assumed they should be since the same app is working for everyone else in the tenant. Any other ideas?

**Comment by SubbaReddi** [comment]
Hi @glblinck,
Navigate to Azure resource group cc app -> Open storage account -> Click on Storage explorer(preview)->Delete "UserData" table and recreate the table.
When you send the message next time user data will be reloaded.
