### ISSUE TITLE
Problem with permissions

### ISSUE THREAD

**Issue by doriansmm97** [OfficeDev/microsoft-teams-apps-company-communicator#555]
I have a problem with the new version, the message is the follow.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/93269313/142696057-f473ad09-6a13-4de7-a8eb-6bf9f9ae9bfd.png)

**Comment by doriansmm97** [comment]
i done the step 3 and 4 with app author

**Comment by Mikhail2k15** [comment]
Looks like it is a custom version of CC not from this repo.

**Comment by doriansmm97** [comment]
with the original version is the same

![image](https://user-images.githubusercontent.com/93269313/142878643-3365114a-6ea9-4b9b-8b22-21e461815d2e.png)

**Comment by priyank29** [comment]
@doriansmm97 please check if the graph permissions are granted.

**Comment by doriansmm97** [comment]
@priyank29 yes, in the app Company Communicator Author
![image](https://user-images.githubusercontent.com/93269313/143263847-486185dd-175a-4e12-939f-de7552896079.png)

**Comment by cristianoag** [comment]
Independent of the version you are using two things can cause the problem you're seeing. 

v5

For v5 you need to check permissions given to the Graph App (from the screenshot you are attaching it looks like you have the correct permissions, but in the Authors App, make sure you have those configured into the Graph App if you are using v5). If you have permissions correctly configured, check the secret for the Graph App. There are two places where you need to check on the App Service (under configuration, check the GraphAppPassword and the AzureAd:ClientSecret. both need to point to the same secret on keyvault). Go to keyvault and make sure the secret is correctly configured there. 

You can easily know if the error is being caused by the wrong secret if you check App Insights for the App Service. There will be an error over there saying that the secret presented to the application is wrong. If your secret is wrong you will also need to update it on the prep function.

v4

With v4 you need to check for the right permissions on the Authors App. We also don't have keyvault for v4, so the secrets will be stored directly on variables under configuration for the App Service (and at least the prep function).

**Comment by satswere** [comment]
@cristianoag i have both ids in my configuration the appservice how can check in keyvault?

**Comment by cristianoag** [comment]
If you want to check keyvault that means you are running v5. I'm also assuming you checked the Graph App registration and all permissions are correctly assigned there. Inside the resource group where you have all CC resources installed there is a keyvault resource. Click it and go to Secrets on the left panel. If you receive a message that secrets cannot be listed you need to give your user permissions to list secrets on keyvault. After doing that, you will see all the secrets configured there. Compare the values with the ones defined for the three applications you configured (User, Authors and Graph).

**Comment by satswere** [comment]
> If you want to check keyvault that means you are running v5. I'm also assuming you checked the Graph App registration and all permissions are correctly assigned there. Inside the resource group where you have all CC resources installed there is a keyvault resource. Click it and go to Secrets on the left panel. If you receive a message that secrets cannot be listed you need to give your user permissions to list secrets on keyvault. After doing that, you will see all the secrets configured there. Compare the values with the ones defined for the three applications you configured (User, Authors and Graph).

amazing thx, was the secrets, working now 😄

**Comment by cristianoag** [comment]
@priyank29 - looks like this one can be closed
