### ISSUE TITLE
Error in sending message to O365 group 

### ISSUE THREAD

**Issue by Ysminali** [OfficeDev/microsoft-teams-apps-company-communicator#562]
Hello,
we have encountered these issues (see image).[
![cc issue](https://user-images.githubusercontent.com/60290491/144043166-efbed5ea-6538-40e6-aaf2-2b232abf16d3.jpg)
](url)

- Getting the following errors/warning when trying to send message to O365 group 
-  number of users in the group only  6 users. 
- All the required permission have been assigned to the application as the below image 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/60290491/144043405-d4b9ca0e-db4d-4cea-a0fb-727b65089313.png)

- Bot has been setup for all users who are member/owner in the group. 

- error synatx 
Failed to prepare the message for sending:The orchestrator function 'SyncRecipientsOrchestrator' failed: The activity function 'BatchRecipientsActivity' failed: Object reference not set to an instance of an object See the function execution logs for additional details. See the function execution logs for additional details.

**Comment by v-royavinash** [comment]
Hi @Ysminali ,

Thanks for raising the query. Could you please try the below steps and let us know if it works? If not, then please share the logs of the “******-prep-function” azure function.

Step 1: 
It generally happens due to permission issues, but I can see you have added all the permission. Please try once with an admin account and just confirm that you have added "Semicolon-delimited list of the user principal names (UPNs)" in AuthorCreatorUpn.

Step 2:
Taking reference to issue #316 please try below step  
In the "Microsoft Teams admin center" go to "Teams apps"->"Manage Apps" and select the Company Communicator author app. After clicking the author app, you can go to the Permissions section and click "Review permissions and consent". This action will grant consent to the author app to read the group's info. Post that re-start the “******-prep-function” azure function.

**Comment by Porkai-Pandian** [comment]
Hi @Ysminali,

Please let us know if you've any updates on the issue
