### ISSUE TITLE
App Not Installed longer then a day

### ISSUE THREAD

**Issue by rex-ma** [OfficeDev/microsoft-teams-apps-company-communicator#586]
We found some users always show "App Not installed" in the log, even the user app deployed longer then 1 day
![image](https://user-images.githubusercontent.com/25476072/147027049-49d0b9fb-8b0c-4a34-8810-0cd84c3dbbc0.png)

Sent message several times, the error still not fix

**Comment by v-royavinash** [comment]
hi @rex-ma,

This issue might occur when the admin reuploads the app to the app catalog by deleting the old one.

- 	Navigate to Azure portal and open company communicator deployed resource group
- 	Click on “Storage account”
- 	Expand “Tables” section
- 	Open “AppConfig” table
- 	Delete the second record where Rowkey is entered as “UserAppId”

So that it populates with the correct value while sending the next message. Let us know if it worked.

**Comment by rex-ma** [comment]
Solution not work for our case

**Comment by Porkai-Pandian** [comment]
Hi @rex-ma,

As per the discussions, it seems the user customized the app and getting issues, please not that we'll not be able to provide support for customized version of the apps.
