### ISSUE TITLE
How to pin Author app on side menu

### ISSUE THREAD

**Issue by siddiquiaslam** [OfficeDev/microsoft-teams-apps-company-communicator#613]
Unable to pin Author app on side menu, any leads? Can pin User app.

**Comment by Porkai-Pandian** [comment]
Hi @siddiquiaslam,

Thank you for raising the query, are you able to access the author app successfully, if the author app is installed, then you should be able to pin the app as well

**Comment by siddiquiaslam** [comment]
> Hi @siddiquiaslam,
> 
> Thank you for raising the query, are you able to access the author app successfully, if the author app is installed, then you should be able to pin the app as well

Hi @Porkai-Pandian 

I am able to access app, but when I right click on Author app, nothing happens. Note that I am able to pin user app. Thanks.

**Comment by Porkai-Pandian** [comment]
Thanks @siddiquiaslam for your response, author apps are installed to Teams channels and groups and not for the user chat, this is the reason you're able to pin user app whereas unable to pin author app. This is expected behavior, please let us know if you've any other queries if not we'll proceed with closing the issue.

**Comment by siddiquiaslam** [comment]
> Thanks @siddiquiaslam for your response, author apps are installed to Teams channels and groups and not for the user chat, this is the reason you're able to pin user app whereas unable to pin author app. This is expected behavior, please let us know if you've any other queries if not we'll proceed with closing the issue.

Thanks for response, closing issue.
