### ISSUE TITLE
Error with deploying teams communicator app

### ISSUE THREAD

**Issue by ChristianHoffmannn** [OfficeDev/microsoft-teams-apps-company-communicator#661]
Hello together,

i tried to implemt the communicator app via powershell in a test tenant for a customer, who wants to use it.
I was successfull until the step "deploying app services, azure function, bot service and other supporting resources".
To show you the error, i uploaded both logs from the deployment log here:
[activity_log.log](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/8216151/activity_log.log)
[deployment_operation.log](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/8216153/deployment_operation.log)

I do not really understand for example, why it says bot name is already registered, when i never used the app before.
In the parameter.json i tried another bot name but the same error still appears.

Has anyone a suggestion for me what i can check?

Kind regards

Chris

**Comment by Porkai-Pandian** [comment]
Hi @ChristianHoffmannn,

Please check if you've deployed the app with the already registered client id, because the error states "The bot name is already registered to another bot application". If you still get the same error after verification, I would recommend creating new app registration for author, user and graph app and start with new deployment.

**Comment by ChristianHoffmannn** [comment]
> Hi @ChristianHoffmannn,
> 
> Please check if you've deployed the app with the already registered client id, because the error states "The bot name is already registered to another bot application". If you still get the same error after verification, I would recommend creating new app registration for author, user and graph app and start with new deployment.

Hi Porkai,
i checked it under app registration, but i did not find there any already deployed app from teams communicator.

Can you please tell me, where i can check this please?

**Comment by robinmeure** [comment]
Hey Chris,

make sure that the name you used in the baseResourceName section of the configuration is unique. 
"baseResourceName": {
    "Value": "<<value>>",
    "Description": "The base name to use for the resources that will be provisioned."
  }

For example, don't use CompanyCommunicator or Contoso, because that already exists globally. 
Instead try to your tenantName to make it unique (e.g. m365x23423423) as naming convention.

**Comment by ChristianHoffmannn** [comment]
Issue is solved. 
Did not know that the baseResourcename is globally, thought it just for the tenant. As i chose another one, which was free, it worked. 
Got a new error ARM template deployment error but the resources got all created. Will check it, if i can work with that.

But that is not a topic for this issue anymore
