### ISSUE TITLE
Company Communicator Deployment Failing using PowerShell 

### ISSUE THREAD

**Issue by shreebharaath** [OfficeDev/microsoft-teams-apps-company-communicator#666]
Hi Team ,

               I retried the same deployment again this time i am getting the below error please help in resolving the issue

![image](https://user-images.githubusercontent.com/39901961/157626567-9501b820-7958-4911-89cd-2187533d3882.png)

**Comment by gsv022** [comment]
Hi @shreebharaath,
[](https://user-images.githubusercontent.com/98143492/157607743-b5fd8666-5cd3-4d4c-b056-ab7e1be3a408.png)The above-mentioned issue occurs sometimes during ARM template deployment. Depending on the resource failed, please follow the below steps,
• App service
• Data-function : Azure function
• Prep-function : Azure function
• Function: Azure function

User can manually fix the issue by following the below steps:
• Go to the Azure portal  Resource group which got created  App Service
• Go to the "Deployment center" section of the app service that failed to deploy.
• Click on "Sync" to restart the deployment.
![image](https://user-images.githubusercontent.com/98143492/157686426-49e12282-4d09-4c11-9fdc-41f39761d827.png)




• Post successful deployment of app service the Status will change as “Success”.
• If you don’t see the Git [URL](https://github.com/OfficeDev/microsoft-teams-company-communicator-app.git) mapped to app service, then please add External Git repo URL and then click on Sync.
• Repeat the same steps for the failed Azure functions as well.

Since deployment failed, users may not have received the authorBotId, userBotId and appDomain values at the end of the deployment. To find them, go to the "Configuration" section of your App Service.
• authorBotId : It can be found in the "AuthorAppId" field of your configuration.
• userBotId : It can be found in the "UserAppId" field of your configuration.
• appDomain : It is the value in the "AzureAd:ApplicationIdURI" field of your configuration without the "api://" e.g. appName.azurefd.net. For the following steps, it will be referred to as %appDomain%.

From here you can continue with the [further steps of deployment.](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide)

**Comment by gsv022** [comment]
Hi @shreebharaath ,
Could you please confirm if the issue logged is fixed and we are good to close the request. If you have any further issue request you to please log another issue.

**Comment by gsv022** [comment]
Hi @shreebharaath ,

Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses.

You may also always open a new issue or respond here if something does come back up. Thank you!
