### ISSUE TITLE
Can I set up the v4.1 branch ?

### ISSUE THREAD

**Issue by ATshirai** [OfficeDev/microsoft-teams-apps-company-communicator#699]
We are using v4.1 Company Communicator.
When we need to resync our Company Communicator, can I set up the v4.1 branch instead of master or v4.1.x?

> In your screenshot above there is a disconnect link. Disconnect then set up a new External git connection with the same repo but instead of master use v4.x branch.
> 
> _Originally posted by @Mikhail2k15 in https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/546#issuecomment-964750554_

**Comment by gsv022** [comment]
Hi @ATshirai , 
 
You won’t be able to set the branch to v4.1 as we don’t have branch with such name in repo. If you planning to deploy version ~4, you can select the branch as v4.x but it will not point to the specific 4.1 version. Instead, it will have the highest 4.x version i.e., v4.1.5. 

Could you please let us know if you see any challenge in deploying v4.1.5 instead of v4.1?

**Comment by ATshirai** [comment]
@gsv022 
Thank you so much for your information.
 I understood that  our company communicator will be v4.1.5 when I resync it with the 4.x branch.
I'm sure I let you know if I see any problems.

(CC:  @MK202204)
