### ISSUE TITLE
How to block downloading of files for all users?

### ISSUE THREAD

**Issue by PrithuMahisha** [OfficeDev/microsoft-teams-apps-company-communicator#732]
I have deployed Company communicator in a tenant and I want to block the download option for all the files sent via company communicator. I believe that we share the files either by using the button by providing the file path in the button URL or directly providing the path in the body of message. Users must only be able to view the files. 
How do I make it possible?

**Comment by JasthiKalyani** [comment]
Hi @PrithuMahisha,

We are looking on this, we will check and let you know.

**Comment by PrithuMahisha** [comment]
> Hi @PrithuMahisha,
> 
> We are looking on this, we will check and let you know.

Hi @JasthiKalyani ,

Is there any update on this?

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
If there is a pdf file in the URL, we are grabbing the link and just attaching the link with the message. The link will be sent to all users. And the user can click on that link, it will be redirected to the pdf file. Read-only or Read and Write, it totally depends on the link that we are attaching. We don't have control over that either to make that page Read-only or Read and Write.

**Comment by PrithuMahisha** [comment]
Is it possible to make it as one of the settings in Company Communicator app itself? I think this needs to be performed in the source code level.

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,

The feature Read-only or Read and Write of a particular page will be considered as a enhancement post the discussion with our internal team. For now if you any issues related to Company Communicator, please let us know. Otherwise we will close out this issue in a 3 business days. You may also always open a new issue or respond here if something does come back up.

Thank you
