### ISSUE TITLE
Time taken to send messages is longer than a day

### ISSUE THREAD

**Issue by nanddeepn** [OfficeDev/microsoft-teams-apps-company-communicator#754]
Hi,

We are using Company Communicator v4.1.5 
It is taking more than 24 hours to complete sending the messages to 90,000 users.

_One quick observation:_
Although in the App Service configuration, `ProactivelyInstallUserApp` is set to `false`, we see _Installing App_ message.

The exported data has below error for failed users in `Status Reason`:
_-2 : System.Net.http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond._

**Comment by v-royavinash** [comment]
@nanddeepn 
Thanks for sharing your observation.
We came across few customers facing similar errors for 4.x. We are checking at our end. We will keep you looped with updates.

**Comment by v-royavinash** [comment]
Hi @nanddeepn ,

The "_System.Net.http.HttpRequestException: A connection attempt failed_" errors was thrown due to the Azure bot services and the issue has been fixed. Could you please re-try sending the messages and share the below observations,

- Volume of target audience
- Time taken to send the messages.
- Connection attempt failed count (If any)

**Comment by nanddeepn** [comment]
Hi @gsv022 
Our comms team sends the communication every Wednesday. I will share the results on next Wednesday.
