### ISSUE TITLE
Unable to Open App after installation

### ISSUE THREAD

**Issue by raghavn** [OfficeDev/microsoft-teams-apps-company-communicator#764]
Downloaded Version 5.x and updated the parameters file
Started deployment using Powershell script
The deployment is successful and got Author app and client app zip file.
Uploaded the author app to Teams.

When trying to open the author app getting error message - The resource you are looking for has been removed, had its name changed, or is temporarily unavailable. 

Any idea on this issues? Kindly help

**Comment by gsv022** [comment]
Hi @raghavn ,
This might happen due to incorrect configuration. Could you please verify the configuration end-end and manifest files too.

**Comment by raghavn** [comment]
@gsv022 , same error is coming when i hit the config tab https url in browser, could you please elaborate what exactly i need to verify.  during deployment of the app using powershell we did not specify any value for UserObjectId in the parameters.json file. could that be an issue?
Also, the powershell deployment script was failing at the section where its performing "Sync only in upgrades & if no source branch conflict detected" [Line no 557], so we commented that code and executed the script again to complete the deployment. Please guide on these

**Comment by v-royavinash** [comment]
Hi @raghavn ,

Go to azure portal --> Resource group --> Overview --> Click on Deployment and check if all the deployment steps was successful. Also please share us the screenshot of the deployment overview.

If any of the resources failed, either the specific resource has to be re-deployed or the entire deployment process has to be repeated.

**Comment by raghavn** [comment]
Hi @v-royavinash ,
I checked the Resource grop -> Overview -> deployment. There is one step got failed. when i did redeploy from Azure portal it failed again with below deployment name. The error description says "The key vault SKU is invalid"
Microsoft.Template-20220609225052

**Comment by v-royavinash** [comment]
Hi @raghavn , The key vault itself is not created, hence the next resources was not deployed. We request you to use different base resource name and try to re-deploy the CC from start. You can deleted the existing resources before redeploying it. We suggest to go ahead with Manual deployment steps as it has better visibility and control on the resources being deployed.

**Comment by v-royavinash** [comment]
@raghavn  The recommended branch is **master** for the latest version.

**Comment by cifofs** [comment]
> Hi @gsv022 , same error is coming when i hit the config tab https url in browser, could you please elaborate what exactly i need to verify. during deployment of the app using powershell we did not specify any value for UserObjectId in the parameters.json file. could that be an issue? Also, the powershell deployment script was failing at the section where its performing "Sync only in upgrades & if no source branch conflict detected" [Line no 557], so we commented that code and executed the script again to complete the deployment. Please guide on these

Hello, I have the same issue....   Could you please help with this?
![image](https://user-images.githubusercontent.com/99551692/173478629-85a7b31e-7c10-4bab-a079-3968f802328a.png)

![image](https://user-images.githubusercontent.com/99551692/173478801-03523247-b0a8-463b-b149-f076a0fbbfff.png)

If I open Kudu, thereis no configtab folder
![image](https://user-images.githubusercontent.com/99551692/173479350-b3056528-3e24-477d-96d3-ad06e6438385.png)

**Comment by gsv022** [comment]
Hi @raghavn,
Could you please check the configuration end-end and there might be chance that any resource has failed.Please Keep us  updated.

**Comment by v-royavinash** [comment]
Hi @cifofs ,

The **wwwroot** directory does not have the required build files, it suggests the app service deployment was not successful.

Could you please share us the deployment status of  app service deployment with screenshot.

- Go to Resource group. Click on the app service
- Go to deployment center. Click on logs and check the status.
- If the status is failed, click on the link and share the complete logs for our troubleshooting.
 
![image](https://user-images.githubusercontent.com/94480537/173641940-9d8159ba-6da2-48ca-815e-00ea26189da7.png)

**Comment by cifofs** [comment]
> 

Hi @gsv022 actually yes

> Hi @cifofs ,
> 
> The **wwwroot** directory does not have the required build files, it suggests the app service deployment was not successful.
> 
> Could you please share us the deployment status of app service deployment with screenshot.
> 
> * Go to Resource group. Click on the app service
> * Go to deployment center. Click on logs and check the status.
> * If the status is failed, click on the link and share the complete logs for our troubleshooting.
> 
> ![image](https://user-images.githubusercontent.com/94480537/173641940-9d8159ba-6da2-48ca-815e-00ea26189da7.png)

Hello @v-royavinash the deployment failed indeed.  The log file:
Command: deploy.cmd
Handling ASP.NET Core Web Application deployment.
Restoring NuGet packages

Welcome to .NET Core 3.1!
---------------------
SDK Version: 3.1.417

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Find out what's new: https://aka.ms/dotnet-whats-new
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
Write your first app: https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
  Determining projects to restore...
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/system.net.networkinformation/index.json'.
  The content at 'https://api.nuget.org/v3-flatcontainer/system.net.networkinformation/index.json' is not a valid JSON object.
    The JSON document is not an object.
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/system.net.networkinformation/index.json'.
  The content at 'https://api.nuget.org/v3-flatcontainer/system.net.networkinformation/index.json' is not a valid JSON object.
    The JSON document is not an object.
C:\Program Files (x86)\dotnet\sdk\3.1.417\NuGet.targets(128,5): error : Failed to retrieve information about 'System.Net.NetworkInformation' from remote source 'https://api.nuget.org/v3-flatcontainer/system.net.networkinformation/index.json'. [C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.sln]
C:\Program Files (x86)\dotnet\sdk\3.1.417\NuGet.targets(128,5): error :   The content at 'https://api.nuget.org/v3-flatcontainer/system.net.networkinformation/index.json' is not a valid JSON object. [C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.sln]
C:\Program Files (x86)\dotnet\sdk\3.1.417\NuGet.targets(128,5): error :   The JSON document is not an object. [C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.sln]
Failed exitCode=1, command=dotnet restore "C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.sln"
An error has occurred during web site deployment.
\r\nC:\Program Files (x86)\SiteExtensions\Kudu\97.40427.5713\bin\Scripts\starter.cmd deploy.cmd
