### ISSUE TITLE
Change of request in CC

### ISSUE THREAD

**Issue by raghavn** [OfficeDev/microsoft-teams-apps-company-communicator#766]
Hi,
We have got below changes requested for Company Communicator app, kindly let know how we can handle the changes including its deployment.

1. Ability to choose image from local system while configuring the message by authors.
2. Remove the option "Send message to everyone in the organization" from config tab

Kindly help in implementing these changes as we are quite to new this app and technology.

**Comment by gsv022** [comment]
Hi @raghavn ,

The feature "Ability to choose image from local system" is going to be added in the upcoming releases. So we consider it to our backlog and take it in future release. And for the second option, we won't be able to assist on the customization part.
If there is any issue with deployment or functionality of Company Communicator, please let us know.

Thank you.

**Comment by raghavn** [comment]
Hi @gsv022, 

Thanks for the update on the ability choose image from local system. Is it going to be included in the next version??,  we are not looking for exact timeline but atleast the ball park like in next 3 months or 6 months if it will be available.

What we would like to know in terms of customization is that, if we make the changes in the code then how do we deploy it back to already existing deployed app. For example, if we make changes in the clientapp which is a react component, then how do we build that and deploy only that part to azure?
It would be really a great help if you could guide us on this.

**Comment by gsv022** [comment]
Hi @raghavn ,
We won't be able to commit any timeline but this feature will be taking up in the upcoming release i.e., 5.2 version.

**Comment by Porkai-Pandian** [comment]
Hi @raghavn, Ability to choose image from local machine will be available in v5.2 which is planned to be released by end of July 2022. If you want to customize any changes, you can fork the main branch and make changes on top of it and sync to your repo in the deployment center of app service and azure functions. This way your existing app will point to your repo and changes will be reflected. Please note that we'll not be able to support any customized version of the app. We'll proceed with closing this issue since the needed response provided, if you've any further questions request to open new issue.
