### ISSUE TITLE
Function and prep function deployment error

### ISSUE THREAD

**Issue by apptemplatequestions** [OfficeDev/microsoft-teams-apps-company-communicator#768]
Dear Company Communicator-team,

one of my customers recently tried to deploy the Company Communicator but ran into the same issue multiple times.

In detail, they deployed the template and multiple times ran into the issue that the function as well as the prep function failed to deploy with a "Bad Request" support.

Could you please advise on how to deploy the app template without running into this error?

Thanks in advance!

**Comment by gsv022** [comment]
Hi @apptemplatequestions ,
User can manually fix the issue by following the below steps:
•	Go to the Azure portal--> Resource group which got created-->Go to App Service
•	Go to the "Deployment center" section of the app service that failed to deploy.
•	Click on "Sync" to restart the deployment.

![image](https://user-images.githubusercontent.com/98143492/173361937-cfb24d5e-90cd-418e-a707-1a58fd09e8f7.png)

 
•	Post successful deployment of app service the Status will change as “Success”.
•	If you don’t see the Git [URL](https://github.com/OfficeDev/microsoft-teams-company-communicator-app.git) mapped to app service, then please add External Git repo URL and then click on Sync.
•	Repeat the same steps for the failed Azure functions as well.

Since deployment failed, users may not have received the authorBotId, userBotId  and appDomain values at the end of the deployment. To find them, go to the "Configuration" section of your App Service.
•	authorBotId : It can be found in the "AuthorAppId" field of your configuration.
•	userBotId : It can be found in the "UserAppId" field of your configuration.
•	appDomain : It is the value in the "AzureAd:ApplicationIdURI" field of your configuration without the "api://" e.g. appName.azurefd.net. For the following steps, it will be referred to as %appDomain%.

From here you can continue with the [further steps of deployment.](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fwiki%2FDeployment-guide&data=04%7C01%7Cv-pogopalakr%40microsoft.com%7C926adf927fe34cc08ad808d9b9925151%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637744860388307386%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EWi5RYSlCWUHF6xPk6SCZx1DU066JbjYAVY9mCMxYcI%3D&reserved=0)
