### ISSUE TITLE
Problems with Consent after app deployment

### ISSUE THREAD

**Issue by enito-ch** [OfficeDev/microsoft-teams-apps-company-communicator#772]
Hi there! 

After the successful deployment of the app, I am not able to start the author app. 

### What I did so far
- I used the manifest which have been generated during the PowerShell-Deployment
- "Company Communicator (Authors)" has been allowed as a custom app using org-wide App Permission Policy
- I granted all admin consents for the apps in the Azure-Portal after the deployment
- App could be added to a MS-Teams Team. 

### What is not working?
I am now having the problem, that I cannot start the app. It looks like something is wrong with the sing-in. 
I can add the "Company Communicator (Authors)" app to an existing MS-Teams Team. However, I cannot start it once it has been added as a tab since I cannot get over the Sign-In (see the following video)

https://user-images.githubusercontent.com/103029137/173878252-735d49b9-edbc-4dcc-b162-c3fc48eaaacf.mp4
### Review App Permission in MS-Teams Admin-Center is not working (error message).
I also tried to review the Consent in the MS-Teams Admin Center under "Manage Apps", but even there I end-up with an error message. 
![troubleshooting](https://user-images.githubusercontent.com/103029137/173878947-53d81cce-af2d-4615-94a3-75c440b075b4.jpg)
After a successful login with a global admin user, I just get the error-message at the top (asking me to contact ms-support).

I could not find anything while googeling so I hope you guys can help me. 
Please let me know should you have any questions or need any further information.

Looking forward to your feedback!

Best,
Mirco

**Comment by v-royavinash** [comment]
Hi @enito-ch ,

There are multiple reason which might be causing the authentication error. Few areas which can be cross verified are,

- Check if the secrets are correctly configured. Go to resource group, then to Key Vault and compare it with the secrets created for all the 3 app registrations.
- Other possibility might be the app service URL getting blocked due to organization policy. Grab the app service URL and try accessing it from the browser. Share us the screen shot of the page with the console logs.

Also, verify the **Set Up authentication steps** of the graph app registration and if needed we can connect over call to troubleshoot it. 

For the second issue, i.e. error which reviewing the policy. You can reach out to Microsoft Customer Support to check why you are not able to review or upload apps.

**Comment by enito-ch** [comment]
Hey @v-royavinash

The "Set up authentication steps" were not done yet. I expected that to be completed during the deployment. 
I configured everything as described in the deployment guide under "Step 3 - Setup authentication steps" and now everything is working like a charm! 

Thanks for your help! much appreciated!

**Comment by enito-ch** [comment]
Hey @v-royavinash

The "Set up authentication steps" were not done yet. I expected that to be completed during the deployment. 
I configured everything as described in the deployment guide under "Step 3 - Setup authentication steps" and now everything is working like a charm! 

Thanks for your help! much appreciated!
