### ISSUE TITLE
Proactively Install user apps 

### ISSUE THREAD

**Issue by Tamilselvan27** [OfficeDev/microsoft-teams-apps-company-communicator#783]
1.During deployment I've set the ProactiveInstalluserapps to "False", so should I have to redeploy the the app after changing it to "True" in order to make it auto installation?
2.During testing (ProactiveInstalluserapps to "False") when tried to utilize "Send in chat to members of teams" ,it automatically installs the user app to the teams users, was that the expected behaviour?

**Comment by JasthiKalyani** [comment]
Hi @Tamilselvan27,

We can change the proactive installation as true in app service please follow the below steps:
Resource group>>App service>>Configuration>>Advanced Edit>>"ProactivelyInstallUserApp" set value as "True".

Regarding 2nd point we will check and get back to you.

**Comment by Tamilselvan27** [comment]
Thanks for the response regarding point 1,but the issue here was I tried the steps which you have mentioned,but after set it to true, it doesn't installs the app to users who hasn't installed it!

**Comment by Sandeep-FED** [comment]
Hi @JasthiKalyani, Can we have any update on the point #2 

> Hi @Tamilselvan27,
> 
> We can change the proactive installation as true in app service please follow the below steps: Resource group>>App service>>Configuration>>Advanced Edit>>"ProactivelyInstallUserApp" set value as "True".
> 
> Regarding 2nd point we will check and get back to you.

Can we have any update on the 2nd point? I'm also encountering similar issue.

**Comment by gsv022** [comment]
Hi @Tamilselvan27 ,
- For Send in chat to members in Team whether proactive installation is set to true/false,  the app will be installed automatically.
-  We can change the proactive installation as true in app service please follow the below steps:
Resource group>>App service>>Configuration>>Advanced Edit>>"ProactivelyInstallUserApp" set value as "True">>Save>>Restart the App Service. Please do the same for Prep-function as well.

**Comment by Tamilselvan27** [comment]
I've followed the steps mentioned but still the failure occurs due to "App Not Installed" error!.

Attached image:
![info](https://user-images.githubusercontent.com/66209612/175996263-2a67d60a-8a39-4d36-81bf-24f8c835bac9.PNG)

**Comment by SankarMicrosoft** [comment]
Hi @Tamilselvan27, 

Please double check if the user app is installed at the tenant level and the require permission for the app is given to the respective users.

Also, this issue might occur when admin reupload the app-to-app catalog by deleting old one. To solve this,
•	Navigate to [Azure portal](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Furl.avanan.click%2Fv2%2F___http%3A%2Fportal.azure.com%2F___.YXAzOmNpdGl1c3RlY2gtcHJvZDphOm86Yjc0NjA2OGEzNWFjNTkxOGFmZmEyZTZjZDBiODMzOWE6Njo2N2MwOmU3MzIxYjViNzI5YmQzY2ZmODc5NmY5MzNmYzc2YzdjZWQ0ZmE2YzliYmNhZDRiMmRhNmY3NWU1YWUyNGQ4ZGU6aDpG&data=05%7C01%7Cv-saramasamy%40microsoft.com%7C6b5e9d7da00e4eb2eeb308da5b2a0161%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637922533244050881%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BOGrAcKWfP1SetEzdM4GEpx%2B8FtZI5jtOnBLm1twXoU%3D&reserved=0) and open company communicator deployed resource group. 
•	Click on “Storage account” 
•	Expand “Tables” section 
•	Open “AppConfig” table 
•	Delete second record where Rowkey is entered as “UserAppId” 

So that it populates with correct value while sending next message.
![image](https://user-images.githubusercontent.com/107609794/177315003-df52b903-d24f-41e2-a618-f248b8b0d487.png)

Please let us know the status after proceeding the above steps.
