### ISSUE TITLE
Error using PowerShell script under "App Secret"

### ISSUE THREAD

**Issue by placido-iv** [OfficeDev/microsoft-teams-apps-company-communicator#799]
![1](https://user-images.githubusercontent.com/105418731/177743159-48230861-5cef-4ed2-89ca-fef99fd542a5.png)

**Comment by gsv022** [comment]
Hi @placido-iv ,

As you facing issue with PowerShell deployment, Can you please try manual deployment steps. Please refer the wiki for the deployment steps. Meanwhile we will be check this scenario and will get back to you with proper response soon.

Thank you.

**Comment by v-royavinash** [comment]
@placido-iv  Due to new release of Azure CLI, we identified issue with the PowerShell deployment script. Also, downgrading the CLI will not work due AzureAD module which doesn’t have a backward compatibility support when Azure session initiated with aadToken in default context.

Meantime we fix the issue and release the updated script to keep you unblocked we would recommend to follow [manual deployment](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide). We will keep you updated with the PS script fix.

**Comment by gsv022** [comment]
Hi @placido-iv ,
Thanks for your patience. For Powershell deployment if Azure CLI installed is of latest version, please uninstall it and try installing version 2.30.0 and continue the deployment.

Please keep us posted on this.

**Comment by placido-iv** [comment]
Hi gsv022,
Thanks for your time solving this. I really appreciate it. I will keep you posted.
