### ISSUE TITLE
Microsoft-teams-apps-company-communicator Issue

### ISSUE THREAD

**Issue by Aish0396** [OfficeDev/microsoft-teams-apps-company-communicator#801]
Hello all,

Kindly find the below issue that we are facing, when we try to deploy Microsoft-teams-apps-company-communicator through Azure PowerShell. We really appreciate your help and  guidance in resolving this issue.
Herewith attaching the screenshot for your reference, please.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/105062667/178013920-616776db-9d72-4c29-9abf-76ef2d481040.png)

Thank you very much in advance.

**Comment by v-royavinash** [comment]
@Aish0396 Due to new release of Azure CLI, we identified issue with the PowerShell deployment script.  Also, downgrading the CLI will not work due AzureAD module which doesn’t have a backward compatibility support when Azure session initiated with aadToken in default context.

Meantime we fix the issue and release the updated script to keep you unblocked we would recommend to follow [manual deployment](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide). We will keep you updated with the PS script fix.

**Comment by Aish0396** [comment]
Thank you @v-royavinash, we will follow the manual deployment and please keep us posted in-case the issue is fixed in PS script.

**Comment by Aish0396** [comment]
Thank you @v-royavinash , the deployment worked well in non Azure CLI method. We can close this issue. Thank you very much!
