### ISSUE TITLE
HTTP Error 500.30 - ANCM In-Process Start Failure

### ISSUE THREAD

**Issue by maye-vargas** [OfficeDev/microsoft-teams-apps-company-communicator#818]
![image](https://user-images.githubusercontent.com/86726190/180883315-48bde8c4-12d7-4da1-899b-daa9154f357e.png)

**Comment by SankarMicrosoft** [comment]
@maye-vargas If you're following the "Custom-domain-option" doc page, and you found the 500.30 error at step 6... then move to step 7 and fill in the ApplicationIdURI and then try step 6 again. That ApplicationIdURI being blank makes the site error when trying to start, so filling in the relevant value makes it work.
If you are getting the error in any other place/situation, please send us the exact scenario that you are getting the error and which step you are getting the error also. it will help us find the root cause quickly and help us to fix it.

**Comment by maye-vargas** [comment]
> 

I am presenting the error at the moment I open the company communicator author application in the team of teams, at the moment of adding it I get that error as you see in the image.
In the same way when I validate the domain on a site, I do not access that domain and already knowing that I add the ApplicationIdURI, it still presents the same problem.

**Comment by gsv022** [comment]
Hi @maye-vargas ,

- Please find the Website URL in App Service section overview.
<img width="944" alt="image" src="https://user-images.githubusercontent.com/98143492/181195049-b4dfa4de-2096-402d-a421-fd30d98a42a2.png">

- Copy the URL and hit it in a browser
- Open the network tab and share the screenshot of the console. The below is the reference.
<img width="824" alt="image" src="https://user-images.githubusercontent.com/98143492/181195385-15e5eeaf-d499-406c-a65e-14d85bd012d6.png">

Keep us posted.

**Comment by maye-vargas** [comment]
I get the following error.
![image](https://user-images.githubusercontent.com/86726190/181244534-237d843b-6a27-4a0d-bf1d-6f0b8baf5f7b.png)

**Comment by maye-vargas** [comment]
cerrado
