### ISSUE TITLE
About where images uploaded from my local machine are stored（v5.2）

### ISSUE THREAD

**Issue by MK202204** [OfficeDev/microsoft-teams-apps-company-communicator#827]
Hi Team,

I would like to ask about the following released features at v5.2.
・Ability to upload image from local machine.
Where are the images uploaded from the "local machine" saved?

Thanks,
(CC: @ATshirai)

**Comment by gsv022** [comment]
Hi @MK202204 ,
In the latest release, we have added the feature "Ability to upload image from the local machine". This means author can upload the image from his local machine with the image size <=1MB.  This option can be seen in the UI like below
![image](https://user-images.githubusercontent.com/98143492/183367151-f9521e78-7922-4b64-9c9c-17b17e8287a4.png)

Hope this helps.

**Comment by MK202204** [comment]
@gsv022 Thank you for your reply!
yes, I understand that author can upload from local machine, not just the image link.
I'm concerned about uploaded images being stored somewhere in the storage of accessible to everyone.
Or is it the same as sending an email with an image file attached?

Regards,

**Comment by gsv022** [comment]
@MK202204 , the existing feature is like adding the URL of the image in image URL section so that image preview will be available, In addition, uploading the image through **upload** option. So we have given two ways for one option either image URL or uploading the image from the local machine. 

The added feature is not related to sending an email with an image file attached.

**Comment by v-royavinash** [comment]
@MK202204 , The uploaded images will be saved in the Azure blobs within private containers. So it won't be accessible to everyone.

**Comment by MK202204** [comment]
@gsv022 @v-royavinash 
Thank you for your replies!
I understood that uploaded images will be stored in CC's internal object storage.
Thanks,
