### ISSUE TITLE
Minor Version Upgrade Instructions

### ISSUE THREAD

**Issue by malimal99** [OfficeDev/microsoft-teams-apps-company-communicator#829]
Besides random answers to post, is there any documentation for minor version upgrades ie. 5.0>5.1>5.2 etc..?

I know about syncing the app service and functions. How do you verify the sync?  I see "Sync Web Apps" in the logs. 

Should I wait for one resource sync to finish before beginning another?
Do I need to update the Teams apps as well?

Thank you for your time.

**Comment by v-royavinash** [comment]
We don’t have any specific documentation for the migration from v5.0 to v5.1 or v5.1 to v5.2.
When you click on Sync it will pull the latest code from the Main branch.

Below are few points which might be helpful:

- Verify the branch name is **Main** not Master. 
![image](https://user-images.githubusercontent.com/94480537/183487568-51d906df-9df9-4c6f-b3dc-92d780033de5.png)

- Click on Sync. To verify is Sync is successful, Go to Deployment Center --> Logs--> View the **Status** of the deployment.
- If by any chance the app service deployment fails, please refer [Troubleshooting Guide #14.](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#14-app-service-deployment-failed-while-sync-operation-with-below-error)
- You can deploy the functions and app service parallelly at a time. 
- Also, its not compulsory to update the manifest and re-upload it. However, we would suggest to update the manifest as well, so that it reflect the actual version of the app.

**Comment by malimal99** [comment]
Thank you for the reply and comments.

**Comment by malimal99** [comment]
Thank you for the reply and comments.
