### ISSUE TITLE
Communicator cannot find any recipients

### ISSUE THREAD

**Issue by oed-mueckek** [OfficeDev/microsoft-teams-apps-company-communicator#833]
Hello! 
We added the Company Communicator to our subscription but we initially made the mistake that we put the secret IDs and not the secret values into the deployment template.

We already changed the 3 secret IDs to the values (AuthorAppPassword, GraphAppPassword and UserAppPassword) and restarted the app service and the funktion apps but that did not help.

Error in the sign in logs of the enterprise app:
![image](https://user-images.githubusercontent.com/110909794/183897077-3d878e8c-05ab-477a-8023-e5399124775a.png)

We can send messages, but there are no recipients und the messages (although the Team has members)
![image](https://user-images.githubusercontent.com/110909794/183897513-764ccad2-6b23-4a3f-abe8-812683fb9496.png)

Any idea why that is not working? :)

**Comment by gsv022** [comment]
Hi @oed-mueckek ,

- Please do make sure that the secret value is being copied instead of  secret ID. 

<img width="756" alt="image" src="https://user-images.githubusercontent.com/98143492/183964972-2ee70545-7a71-44eb-a8df-64d7c45d0729.png">

- The copied secret value in author app/user app should be pasted in configuration of app service. The same has to be done for prep-function and data function as well.
<img width="752" alt="image" src="https://user-images.githubusercontent.com/98143492/183973236-63b6cf0d-0f62-4a5c-a290-cc961af2cbc8.png">

- The graph app secret has  to be pasted in app service, prep-function
<img width="721" alt="image" src="https://user-images.githubusercontent.com/98143492/183975904-550e24de-a2b8-43ae-90e9-1e71aacd02e7.png">
<img width="781" alt="image" src="https://user-images.githubusercontent.com/98143492/183978251-54150643-04ab-4eae-8c42-a979b2f53c85.png">


- Re-sync the app service and function apps again.

Please let us know if the issue persists.

**Comment by gsv022** [comment]
Hi @oed-mueckek,
There might be possibility that secrets might have missed in some places. Could you please share the teams id, so that we can discuss more on this.

Thank you.
