### ISSUE TITLE
Company communicator permissions for M365 groups, and Teams Admins

### ISSUE THREAD

**Issue by lenamasdo** [OfficeDev/microsoft-teams-apps-company-communicator#883]
Hi, after deploying Company Communicator, im seeing this errors and messages related to permissions:

![image](https://user-images.githubusercontent.com/114112901/192303645-422b862a-dd36-4363-9abc-4051071edec6.png)

![image](https://user-images.githubusercontent.com/114112901/192303948-881a1ca3-42af-45e3-b1e8-8e9aadf9fe38.png)

Any help?

**Comment by v-royavinash** [comment]
Hi @lenamasdo,

Please refer troubleshooting guide issue#3, 

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#3-send-in-chat-to-members-of-the-following-m365-groups-distribution-groups-or-security-groups-option-is-disabled

**Comment by lenamasdo** [comment]
> Hi @lenamasdo,
> 
> Please refer troubleshooting guide issue#3,
> 
> https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#3-send-in-chat-to-members-of-the-following-m365-groups-distribution-groups-or-security-groups-option-is-disabled

Hi, Tried this on the Author API, still doesn't work. Any suggestions?

**Comment by v-royavinash** [comment]
This is the primary root cause of the 4th option to be disabled. Please cross verify if you have granted the admin consent. Also please confirm the same by sharing a screen shot. Also, as per Microsoft guidelines it might take up to 48 hours to reflect the permission. 

The other and only possibility is the secret of the graph app registrations is incorrectly configured. Please cross verify if the secret of the graph app is correctly copied and used during the deployment.
