### ISSUE TITLE
Upgrading from 5.1 to 5.2

### ISSUE THREAD

**Issue by alexl-2397** [OfficeDev/microsoft-teams-apps-company-communicator#888]
Hi, I've tried to upgrade from 5.1 to 5.2, however it doesn't appear to be working.
I've added the REACT_APP settings, and the WEBSITE_NODE_DEFAULT_VERSION is 16.13.0
<img width="519" alt="image" src="https://user-images.githubusercontent.com/105488615/193777249-21a7fc2c-5b02-46f8-95c2-2ab616b2cda1.png">
I then performed a sync from Deployment Center.
I also had to manually update each Azure Function to 16.13.0
<img width="750" alt="image" src="https://user-images.githubusercontent.com/105488615/193777560-6ce8863e-faad-4289-9f54-0c48bfeb5f59.png">
I also performed a sync after this (via Deployment Center)

However the app isn't updating - or at least I've no upload feature on the Author bot.
Thank you.

**Comment by gsv022** [comment]
Hi @alexl-2397 ,
Thanks for raising the query. It seems that you have updated the CC to 5.2 from 5.1 as per the [deployment guide.](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v5x-to-latest-version) Could you please send the screenshot of App service deployment center repo URL and branch it is pointing to and logs status as well.
<img width="697" alt="image" src="https://user-images.githubusercontent.com/98143492/193822704-622d8437-1e1a-4be4-b0f1-43affc64d242.png">

**Comment by v-royavinash** [comment]
The branch name is pointing to master which has been updated to **main** due to GitHub recomendation. Please follow the below steps for the app service and 3 azure functions,

Go to the Deployment center. Click on Disconnect.
![image](https://user-images.githubusercontent.com/94480537/193871644-425b8f62-efc9-42ae-b9a9-6a2effe2380d.png)

Wait for 5 to 10 minutes until the entry under the Logs tab will be deleted automatically.
![image](https://user-images.githubusercontent.com/94480537/193871734-1b4f6e65-feb5-498b-a624-aa958775a67c.png)

Once the disconnection is completed. Go to Settings and select External Git and add below URL and branch name.

Repository : https://github.com/OfficeDev/microsoft-teams-apps-company-communicator.git
Branch : **main** (If you are using older version of CC, please select the branch name accordingly.)
![image](https://user-images.githubusercontent.com/94480537/193872306-80d9138b-ddfb-4fdb-a46d-89a3cc95e8e0.png)

Repeat the same steps for other azure functions. Sing out from teams and then sign in to see the latest changes.

**Comment by alexl-2397** [comment]
Hi @v-royavinash, thanks for the response.
I've done the above on the App Service and all 3 Azure functions, performed a sync and restarted them also.
<img width="638" alt="image" src="https://user-images.githubusercontent.com/105488615/194040142-6a08b014-9ce5-4060-b548-737aeed98a18.png">
<img width="908" alt="image" src="https://user-images.githubusercontent.com/105488615/194040182-e3ba248a-b19b-44ce-bb73-b7911f39c507.png">

I still have no upload function on the author app - however I'm willing to give it time just in case.
<img width="734" alt="image" src="https://user-images.githubusercontent.com/105488615/194040327-a1a2bbf8-fc10-407d-b3a8-9f1a95c949ba.png">

**Comment by alexl-2397** [comment]
<img width="849" alt="image" src="https://user-images.githubusercontent.com/105488615/194087848-7cb57273-cfb3-403e-8132-3cd5a04146f1.png">
I'm wondering if this is related, or if its okay to do this?

**Comment by victorsimonlee** [comment]
@alexl-2397  - I know this is silly, but did you also restart your Teams client? It is required to load the new version.

**Comment by v-royavinash** [comment]
@alexl-2397  The warning mentioned in the Azure function is not related to the issue. Can you please try login to Teams through web browser and check if you are able to see the updated UI for v5.2

**Comment by alexl-2397** [comment]
Hi @v-royavinash 
Looks good in the web version! 
<img width="732" alt="image" src="https://user-images.githubusercontent.com/105488615/194257603-1befa064-1ee8-4598-a119-69a257a5a5c4.png">
I'm assuming its just cached on my machine which is why it's not appearing.

Relating to the Azure Function warning, is it safe to upgrade to 4x as per the suggestion in the warning?
Thank you.

**Comment by alexl-2397** [comment]
I've cleared the Teams cache and it's now appearing in the desktop client.
Thank you for your help on this matter.
