### ISSUE TITLE
about to secure domain fronting 

### ISSUE THREAD

**Issue by ATshirai** [OfficeDev/microsoft-teams-apps-company-communicator#897]
Hello Devs.

I am using  Company Communicator v4.1.0. 
I think that we need to secure domain fronting because Company Communicator uses Azure Front Door (Classic).

[Securing our approach to domain fronting within Azure](https://www.microsoft.com/security/blog/2021/03/26/securing-our-approach-to-domain-fronting-within-azure/)

I understand If the value of the SNI parameter  is different than the value of  Host parameter, the TLS packet is rejected.
I need to know if the values of the HOST parameter and SNI parameter the same in the TLS  of Company Communicator.

Regards,
 
(CC: @MK202204)

**Comment by ATshirai** [comment]
Hi, @gsv022 ,
Thanks for your checking into this issue.
 If you don't mind, please let me know what the status is.

**Comment by ATshirai** [comment]
Hi, @gsv022 
Do you have any information that Company Communicator's front door resource  deployed after April 29,2022 doesn't work well ?
Do you have any informations that Company Communicator's front door resource  deployed after April 29,2022 doesn't work well ?
Microsoft says after April 29,2022, there are two kinds of Front Door.
One is Front Door(classic) , it has been disabled Domain Fronting.
Another is Front Door, it is enabled Domain Fronting.
If Company Communicator is deployed after April 29,2022, and it works fine, 
I think Company Communicator is  unaffected by Domain Fronting.

**Comment by v-royavinash** [comment]
@ATshirai,  Since 29 April 2022, Microsoft has changed the behaviours of Azure Front Door to align with the [commitment](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fsecurity%2Fblog%2F2021%2F03%2F26%2Fsecuring-our-approach-to-domain-fronting-within-azure%2F&data=05%7C01%7Cv-royavinash%40microsoft.com%7C42dc29912edb4ce1a03208dac34280e8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638036987693170470%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eSwt5DT6Hsz7ubHe7Czjw1a2XvMiKFxPIUdE5NNED7w%3D&reserved=0) to stop allowing domain fronting. With that change, an option to enable blocking domain fronting for existing or newly created Azure Front Door, was provided, through opening an Azure support request.

Front doors created before 8th November 2022 will not have any impact until 8th November **2023**. Beginning 8 November 2022, all the newly created Azure Front Door (classic) resources will block any HTTP request that exhibits [domain fronting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fazure%2Ffrontdoor%2Ffront-door-faq%23how-does-front-door-handle--domain-fronting--behavior--&data=05%7C01%7Cv-royavinash%40microsoft.com%7C42dc29912edb4ce1a03208dac34280e8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638036987693170470%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0G2OoTSIQsp7cD1dxtvZd4feO2kd5v%2BaWSjzXvPK1gU%3D&reserved=0) [behaviour](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fazure%2Ffrontdoor%2Ffront-door-faq%23how-does-front-door-handle--domain-fronting--behavior--&data=05%7C01%7Cv-royavinash%40microsoft.com%7C42dc29912edb4ce1a03208dac34280e8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638036987693170470%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0G2OoTSIQsp7cD1dxtvZd4feO2kd5v%2BaWSjzXvPK1gU%3D&reserved=0). It is **expected** that it won’t affect the working of Company Communicator however we are reviewing the impact on architecture and functionality and will keep you posted with the observations.

Allow us to review completely and we will provide response for the query related to values of the HOST parameter and SNI parameter.

**Comment by ATshirai** [comment]
Hi, @v-royavinash  and Teams.
Could you please let me know  when you are planning to complete your review ?

**Comment by ATshirai** [comment]
@v-royavinash 

I'm really appreciate it.
I'm so glad to recive the reply  that We don't see any impact on the Azure front doors created in CC.
We are facing no issue on our CC. 
But we have the plan to enable domain fronting fix, so I have needed to post this issue.

Thanks again  for your team to review the domain fronting impact .

**Comment by v-royavinash** [comment]
@ATshirai Do you have any other queries related to Company Communicator? If not, we can proceed to close the issue.
