### ISSUE TITLE
about Azure Static Web Apps support for Node 12 ends

### ISSUE THREAD

**Issue by ATshirai** [OfficeDev/microsoft-teams-apps-company-communicator#898]
Hi teams.

I found the following support end announce from Microsoft support . 

[Azure Static Web Apps support for Node 12 ends on 3 December 2022](https://azure.microsoft.com/ja-jp/updates/staticwebappsnode12deprecation/)

I am using Company Communicator v4.1.0. 
Do I need to do anything about it ?
After 3 December 2022, can I  continue to use my Company Communicator, also to resync it with v4.1.x when I need to do ?

Best regards

(CC: @MK20422)

**Comment by gsv022** [comment]
Hi @ATshirai ,
Could you please update the node of that particular app service to **14** . For 4.x version we have not tested with node 14 but please check it at your end in test environment and then go for production environment. If it is causing the issue at 4.x version then it is recommended to upgrade the app from 4.x to **5.x** version. Because 5.x version supports node **14**.

**Comment by ATshirai** [comment]
Hi, @gsv022 

Thank you  for your advices.
But I have no Company Communicator on the test environment, just only the production Company Communicator.
Also, I don't know how to update Node 12 to Node 14.
What do I do it?

Best Regards

(CC: @MK20422 )

**Comment by ATshirai** [comment]
Hi, @v-royavinash 

I need to know  how to update Node 12  where our Company Communicator v4.1 works on to Node 14.
What do I do it?

Best Regards

(CC: @MK20422 )

**Comment by gsv022** [comment]
Hi @ATshirai ,
It is recommended(not mandatory) to upgrade the app version from 4.x to 5.x version i.e., 5.2 where  it supports not only the node version 14 but also more secured with added features. 

Thank you.
