### ISSUE TITLE
Removing "send to everyone in chat" option

### ISSUE THREAD

**Issue by glblinck** [OfficeDev/microsoft-teams-apps-company-communicator#959]
Is there a way to remove the "send in chat to everyone" field in the authoring app? This is being used in a shared tenant where nobody should be sending any messages to all recipients.

![image](https://user-images.githubusercontent.com/61463212/215914920-a7409eed-4869-4208-a4eb-11eecbdff8ba.png)

**Comment by gsv022** [comment]
Hi @glblinck ,
Thanks for raising the query. Yes, this can be done. One way is doing the modifications at the code level. Other way is mentioned in the below steps
- Make the proactive installation **false.** Go to Azure Portal-->Open the resource group where CC was deployed-->Click on App service-->Go to Configuration-->Set the proactive installation to false
<img width="721" alt="image" src="https://user-images.githubusercontent.com/98143492/215964542-740f6c9e-b42e-4297-ba99-898cdece6053.png">

- Normally, we upload the user app at the tenant level instead of that add the user app at the teams level(to the team you want to add) not at the tenant level.
- The above two steps will help you in solving the issue.

**Comment by glblinck** [comment]
I'm not trying to block people in the tenant from getting the app, since different groups in the tenant send communications to different groups of users. All the users would need the client. I think the code level is where I'd have to go, just removing the option to send to all. I would need everyone able to receive a message in the tenant.

**Comment by glblinck** [comment]
Hi @gsv022,
Thank you! That's what I was looking for.
