### ISSUE TITLE
Error after renewing the secret cert

### ISSUE THREAD

**Issue by TomSawyer03** [OfficeDev/microsoft-teams-apps-company-communicator#962]
Error after renewing the secret cert
error message

The orchestrator function 'SyncRecipientsOrchestrator' failed: "The activity function 'BatchRecipientsActivity' failed: "Object reference not set to an instance of an object.". See the function execution logs for additional details.". See the function execution logs for additional details. <--- The activity function 'BatchRecipientsActivity' failed: "Object reference not set to an instance of an object.". See the function execution logs for additional details. <--- Object reference not set to an instance of an object.

![image](https://user-images.githubusercontent.com/85331597/217433743-69565707-8333-45e6-9812-089d543435f5.png)

**Comment by gsv022** [comment]
Hi @TomSawyer03 ,
Thanks for raising the query. Please respond to the below queries.

- What is the version of the app?
- Check whether the secret is updated in respective places or not. If the version installed is of 5.x, here is the procedure for updating the [secret](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/911). Hope you have followed this.
- Especially if the graph app secret got expired please update the same in AzureAd client secret, which is nothing but graph app password. Here is the reference. 
<img width="633" alt="image" src="https://user-images.githubusercontent.com/98143492/217463097-961045e9-7856-43ea-959a-fde945545246.png">

- If the error persists, please share the outlook id  so that we can discuss the issue by getting into the call if needed.

**Comment by TomSawyer03** [comment]
*   What is the version of the app?
5.0.0

  *   Check whether the secret is updated in respective places or not. If the version installed is of 5.x, here is the procedure for updating the secret<https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/911>. Hope you have followed this.
Yes I did. But still we are getting the below error message.
Failed to prepare the message for sending:The orchestrator function 'SyncRecipientsOrchestrator' failed: "The activity function 'BatchRecipientsActivity' failed: "Object reference not set to an instance of an object.". · Issue #932 · OfficeDev/microsoft-teams-apps-company-communicator · GitHub<https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/932>
***@***.***

  *   Especially if the graph app secret got expired please update the same in AzureAd client secret, which is nothing but graph app password. Here is the reference.
Yes I did,

Can we have a quick call so I can show you our configurations?

**Comment by gsv022** [comment]
Please share you Outlook Id so that we can discuss internally on this issue.

**Comment by TomSawyer03** [comment]
Rtomas@archgroup.com

> Please share you Outlook Id so that we can discuss internally on this issue.

**Comment by gsv022** [comment]
Attended the call and resolved the issue. Please let us know if you still needs inputs from our side otherwise we are good to close out the issue.

**Comment by dahazeman** [comment]
It is stated that the issue was resolved after a call. What was the solution? We have this same problem.
