### ISSUE TITLE
User and Author Bot

### ISSUE THREAD

**Issue by yeeydu** [OfficeDev/microsoft-teams-apps-company-communicator#973]
Hi, Is there a specific reason to use two bots ?  
Can I have a practical example for the advantages of using two bots ? and if we try to merge them together will it work ?

I Read this from the documentation:

Author Bot Registration: The Author Bot registration is used for author's app. The application is separated from the User application so that different teams policies can be applied.
User Bot Registration: The User Bot registration is used for user's app, which is installed by users to receive messages send by Company Communicator application.

Is this the main reason or there are more ?

Thanks

**Comment by gsv022** [comment]
Hi @yeeydu ,
Thanks for raising the query.  

- The role of author bot is to broadcast the messages in four different ways-  At organization level,  To individual members of the team, as a general post or To a specific team.
**Note**:- Proactive installation must be set to true so that user app will be installed automatically to the users for whom we intend to deliver the message.

- The role of user bot is only to receive the message and wont allow sending the message again. So its a one-way communication.
- No, it is not possible to merge the two bots.

**Comment by gsv022** [comment]
@yeeydu , We are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
