### ISSUE TITLE
Teamdata not populating when app is installed

### ISSUE THREAD

**Issue by JFus8** [OfficeDev/microsoft-teams-apps-company-communicator#997]
I ran the "Add-TeamsAppInstallation" PowerShell script to install the communicator app to all of our Teams but the "teamdata" table only populated the Teams that I'm personally a member of.  I did verify the app is installed on each Teams site. If the user app is installed manually it does populate into the database table. Anyone else run into this because manually entering each team is not viable when you have 500+ sites.  Any help is appreciated.

**Comment by gsv022** [comment]
Hi @JFus8,
Thanks for raising the query. This will not work because when a user app is added to the particular team internally a piece of code will create a entry in the database.  So it is not suggested to implement it through the PowerShell script

**Comment by JFus8** [comment]
What is your suggestion for adding it to multiple Teams sites?

**Comment by v-royavinash** [comment]
@JFus8, As mentioned above, the normal process is to do it manually. Using PowerShell it will not work because an entry is created against each team in the backend. If you have enabled Proactive installation, you can directly search the team name using the fourth option of the Author app, and the user bot installation will be taken care of during the send operation of the message. Please note that Proactive installation is mandatory for this approach.
